//$file${.::reminder2.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: reminder2.qm
// File:  ${.::reminder2.c}
//
// This code has been generated by QM 7.0.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::reminder2.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpc.h"
#include "bsp.h"

#include "safe_std.h" // portable "safe" <stdio.h>/<string.h> facilities
#include <stdlib.h>

//Q_DEFINE_THIS_FILE

//..........................................................................
enum ReminderSignals {
    CRUNCH_SIG = Q_USER_SIG, // the invented reminder signal
    ECHO_SIG,                // check the responsiveness of the system
    TERMINATE_SIG            // terminate the application
};

//$declare${Events::ReminderEvt} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Events::ReminderEvt} .....................................................
typedef struct {
// protected:
    QEvt super;

// public:

    // the next iteration to perform
    uint32_t iter;
} ReminderEvt;

// public:
static inline ReminderEvt * ReminderEvt_init(ReminderEvt * const me,
    uint32_t iter)
{
    if (me != (ReminderEvt *)0) {
        me->iter = iter;
    }
    return me;
}
//$enddecl${Events::ReminderEvt} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//..........................................................................
//$declare${Components::Cruncher} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Components::Cruncher} ....................................................
typedef struct {
// protected:
    QActive super;

// private:

    // internal variable
    double sum;
} Cruncher;

// public:
static void Cruncher_ctor(Cruncher * const me);

// protected:
static QState Cruncher_initial(Cruncher * const me, void const * const par);
static QState Cruncher_processing(Cruncher * const me, QEvt const * const e);
static QState Cruncher_final(Cruncher * const me, QEvt const * const e);
//$enddecl${Components::Cruncher} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${Components::Cruncher} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Components::Cruncher} ....................................................

//${Components::Cruncher::ctor} ..............................................
static void Cruncher_ctor(Cruncher * const me) {
    QActive_ctor(&me->super, Q_STATE_CAST(&Cruncher_initial));
}

//${Components::Cruncher::SM} ................................................
static QState Cruncher_initial(Cruncher * const me, void const * const par) {
    //${Components::Cruncher::SM::initial}
    (void)par; // unused parameter

    QS_FUN_DICTIONARY(&Cruncher_processing);
    QS_FUN_DICTIONARY(&Cruncher_final);

    return Q_TRAN(&Cruncher_processing);
}

//${Components::Cruncher::SM::processing} ....................................
static QState Cruncher_processing(Cruncher * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${Components::Cruncher::SM::processing}
        case Q_ENTRY_SIG: {
            #ifdef QEVT_PAR_INIT
            ReminderEvt *reminder = Q_NEW(ReminderEvt, CRUNCH_SIG, 0U);
            #else
            ReminderEvt *reminder = Q_NEW(ReminderEvt, CRUNCH_SIG);
            reminder->iter = 0U;
            #endif

            QACTIVE_POST(&me->super, &reminder->super, me);
            me->sum = 0.0;
            status_ = Q_HANDLED();
            break;
        }
        //${Components::Cruncher::SM::processing::CRUNCH}
        case CRUNCH_SIG: {
            uint32_t i = Q_EVT_CAST(ReminderEvt)->iter;
            uint32_t n = i;
            i += 100U;
            for (; n < i; ++n) {
                if ((n & 1) == 0) {
                    me->sum += 1.0/(2*n + 1);
                }
                else {
                    me->sum -= 1.0/(2*n + 1);
                }
            }
            //${Components::Cruncher::SM::processing::CRUNCH::[i<0x07000000U]}
            if (i < 0x07000000U) {
                #ifdef QEVT_PAR_INIT
                ReminderEvt *reminder = Q_NEW(ReminderEvt, CRUNCH_SIG, i);
                #else
                ReminderEvt *reminder = Q_NEW(ReminderEvt, CRUNCH_SIG);
                reminder->iter = i;
                #endif

                QACTIVE_POST(&me->super, &reminder->super, me);
                status_ = Q_HANDLED();
            }
            //${Components::Cruncher::SM::processing::CRUNCH::[else]}
            else {
                PRINTF_S("pi=%16.14f\n", 4.0 * me->sum);
                status_ = Q_TRAN(&Cruncher_processing);
            }
            break;
        }
        //${Components::Cruncher::SM::processing::ECHO}
        case ECHO_SIG: {
            PRINTF_S("Echo! pi=%16.14f\n", 4.0 * me->sum);
            status_ = Q_HANDLED();
            break;
        }
        //${Components::Cruncher::SM::processing::TERMINATE}
        case TERMINATE_SIG: {
            status_ = Q_TRAN(&Cruncher_final);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${Components::Cruncher::SM::final} .........................................
static QState Cruncher_final(Cruncher * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${Components::Cruncher::SM::final}
        case Q_ENTRY_SIG: {
            PRINTF_S("%s\n", "final-ENTRY;");
                     QF_stop(); // terminate the application
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
//$enddef${Components::Cruncher} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

// test harness ============================================================

// Local-scope objects -----------------------------------------------------
static Cruncher l_cruncher; // the Cruncher active object

//..........................................................................
int main(int argc, char *argv[]) {
    PRINTF_S("Reminder state pattern\nQP version: %s\n"
           "Press 'e' to echo the current value...\n"
           "Press ESC to quit...\n",
           QP_VERSION_STR);

    BSP_init(argc, argv); // initialize the BSP

    QF_init();// initialize the framework and the underlying RT kernel

    // publish-subscribe not used, no call to QF_psInit()

    static QF_MPOOL_EL(ReminderEvt) smlPoolSto[20]; // small pool storage
    QF_poolInit(smlPoolSto, sizeof(smlPoolSto), sizeof(smlPoolSto[0]));

    // instantiate and start the active objects...
    Cruncher_ctor(&l_cruncher);
    QEvtPtr cruncherQSto[10]; // event queue storage for Cruncher AO
    QActive_start(&l_cruncher.super,
                  1U,
                  cruncherQSto, Q_DIM(cruncherQSto),
                  (void *)0, 0U, (QEvt *)0);

    return QF_run(); // run the QF application
}
//..........................................................................
void BSP_onKeyboardInput(uint8_t key) {
    switch (key) {
        case 'e': { // 'e' pressed -> post the ECHO event
            // NOTE:
            // Posting the ECHO event would be best handled with an
            // immutable event, as it is illustrated in the next case
            // of the TERMINATE event below (case '\033').
            //
            // However, for the sake of demonstrating the Q_NEW_X()
            // facility, the ECHO event is allocated dynamically, which
            // is allowed to fail because the ECHO event is not
            // considered critical.
        #ifdef QEVT_PAR_INIT
            QEvt const *echoEvt = Q_NEW_X(QEvt, 2U, ECHO_SIG, 0U);
        #else
            QEvt *echoEvt = Q_NEW_X(QEvt, 2U, ECHO_SIG);
        #endif
            if (echoEvt != (QEvt *)0) { // event allocated successfully?
                QACTIVE_POST_X((QActive *)&l_cruncher, echoEvt, 2U, (void *)0);
            }
            break;
        }
        case '\033': { // ESC pressed?
            // NOTE: this immutable event is statically pre-allocated.
            // It can be posted/published as any other event.
            static QEvt const terminateEvt = QEVT_INITIALIZER(TERMINATE_SIG);
            QACTIVE_POST((QActive *)&l_cruncher, &terminateEvt, (void *)0);
            break;
        }
    }
}
