//$file${.::bsp.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: real-time-ms.qm
// File:  ${.::bsp.h}
//
// This code has been generated by QM 7.0.2 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::bsp.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef BSP_H_
#define BSP_H_

#define BSP_TICKS_PER_SEC 5000U

void BSP_init(void const * const arg);
void BSP_start(void);

void BSP_d1on(void);
void BSP_d1off(void);

void BSP_d2on(void);
void BSP_d2off(void);

void BSP_d3on(void);
void BSP_d3off(void);

void BSP_d4on(void);
void BSP_d4off(void);

void BSP_d5on(void);
void BSP_d5off(void);

void BSP_d6on(void);
void BSP_d6off(void);

void BSP_d7on(void);
void BSP_d7off(void);

// immutable events for Periodic active objects
QEvt const *BSP_getEvtPeriodic1(uint8_t num);
QEvt const *BSP_getEvtPeriodic4(uint8_t num);

#endif // BSP_H_
