//$file${.::philo.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: dpp.qm
// File:  ${.::philo.c}
//
// This code has been generated by QM 7.0.3 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::philo.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpc.h"      // QP/C real-time event framework
#include "bsp.h"      // Board Support Package
#include "app.h"      // Application interface

Q_DEFINE_THIS_FILE

//----------------------------------------------------------------------------
// helper function to provide a randomized think time for Philos
static QTimeEvtCtr think_time(void); // prototype
static inline QTimeEvtCtr think_time(void) {
    return (QTimeEvtCtr)((BSP_random() % BSP_TICKS_PER_SEC)
                                        + (BSP_TICKS_PER_SEC/2U));
}

// helper function to provide a randomized eat time for Philos
static QTimeEvtCtr eat_time(void); // prototype
static inline QTimeEvtCtr eat_time(void) {
    return (QTimeEvtCtr)((BSP_random() % BSP_TICKS_PER_SEC)
                                        + BSP_TICKS_PER_SEC);
}
//----------------------------------------------------------------------------
//$declare${AOs::Philo} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Philo} ..............................................................
typedef struct Philo {
// protected:
    QMActive super;

// private:
    QTimeEvt timeEvt;
    uint8_t id;

// public:
} Philo;

extern Philo Philo_inst[N_PHILO];

// protected:
static QState Philo_initial(Philo * const me, void const * const par);
static QState Philo_thinking  (Philo * const me, QEvt const * const e);
static QState Philo_thinking_e(Philo * const me);
static QState Philo_thinking_x(Philo * const me);
static QMState const Philo_thinking_s = {
    QM_STATE_NULL, // superstate (top)
    Q_STATE_CAST(&Philo_thinking),
    Q_ACTION_CAST(&Philo_thinking_e),
    Q_ACTION_CAST(&Philo_thinking_x),
    Q_ACTION_NULL  // no initial tran.
};
static QState Philo_hungry  (Philo * const me, QEvt const * const e);
static QState Philo_hungry_e(Philo * const me);
static QMState const Philo_hungry_s = {
    QM_STATE_NULL, // superstate (top)
    Q_STATE_CAST(&Philo_hungry),
    Q_ACTION_CAST(&Philo_hungry_e),
    Q_ACTION_NULL, // no exit action
    Q_ACTION_NULL  // no initial tran.
};
static QState Philo_eating  (Philo * const me, QEvt const * const e);
static QState Philo_eating_e(Philo * const me);
static QState Philo_eating_x(Philo * const me);
static QMState const Philo_eating_s = {
    QM_STATE_NULL, // superstate (top)
    Q_STATE_CAST(&Philo_eating),
    Q_ACTION_CAST(&Philo_eating_e),
    Q_ACTION_CAST(&Philo_eating_x),
    Q_ACTION_NULL  // no initial tran.
};
//$enddecl${AOs::Philo} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 800U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 8.0.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${App::Philo_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${App::Philo_ctor} .........................................................
void Philo_ctor(uint_fast8_t const id) {
    Philo * const me = &Philo_inst[id];
    QMActive_ctor(&me->super, Q_STATE_CAST(&Philo_initial));
    QTimeEvt_ctorX(&me->timeEvt, Q_ACTIVE_UPCAST(me), TIMEOUT_SIG, 0U),
    me->id = (uint8_t)id;
}
//$enddef${App::Philo_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${App::AO_Philo[N_PHILO]} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${App::AO_Philo[N_PHILO]} ..................................................
QActive * const AO_Philo[N_PHILO] = {
    Q_ACTIVE_UPCAST(&Philo_inst[0]),
    Q_ACTIVE_UPCAST(&Philo_inst[1]),
    Q_ACTIVE_UPCAST(&Philo_inst[2]),
    Q_ACTIVE_UPCAST(&Philo_inst[3]),
    Q_ACTIVE_UPCAST(&Philo_inst[4])
};
//$enddef${App::AO_Philo[N_PHILO]} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::Philo} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Philo} ..............................................................
Philo Philo_inst[N_PHILO];

//${AOs::Philo::SM} ..........................................................
static QState Philo_initial(Philo * const me, void const * const par) {
    //${AOs::Philo::SM::initial}
    Q_UNUSED_PAR(par);

    QS_OBJ_ARR_DICTIONARY(&Philo_inst[me->id], me->id);
    QS_OBJ_ARR_DICTIONARY(&Philo_inst[me->id].timeEvt, me->id);

    QActive_subscribe(Q_ACTIVE_UPCAST(me), EAT_SIG);
    QActive_subscribe(Q_ACTIVE_UPCAST(me), TEST_SIG);

    QS_FUN_DICTIONARY(&Philo_thinking);
    QS_FUN_DICTIONARY(&Philo_hungry);
    QS_FUN_DICTIONARY(&Philo_eating);

    static struct {
        QMState const *target;
        QActionHandler act[2];
    } const tatbl_ = { // tran-action table
        &Philo_thinking_s, // target state
        {
            Q_ACTION_CAST(&Philo_thinking_e), // entry
            Q_ACTION_NULL // zero terminator
        }
    };
    return QM_TRAN_INIT(&tatbl_);
}

//${AOs::Philo::SM::thinking} ................................................
//${AOs::Philo::SM::thinking}
static QState Philo_thinking_e(Philo * const me) {
    QTimeEvt_armX(&me->timeEvt, think_time(), 0U);
    return QM_ENTRY(&Philo_thinking_s);
}
//${AOs::Philo::SM::thinking}
static QState Philo_thinking_x(Philo * const me) {
    (void)QTimeEvt_disarm(&me->timeEvt);
    return QM_EXIT(&Philo_thinking_s);
}
//${AOs::Philo::SM::thinking}
static QState Philo_thinking(Philo * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Philo::SM::thinking::TIMEOUT}
        case TIMEOUT_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[3];
            } const tatbl_ = { // tran-action table
                &Philo_hungry_s, // target state
                {
                    Q_ACTION_CAST(&Philo_thinking_x), // exit
                    Q_ACTION_CAST(&Philo_hungry_e), // entry
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        //${AOs::Philo::SM::thinking::EAT, DONE}
        case EAT_SIG: // intentionally fall through
        case DONE_SIG: {
            // EAT or DONE must be for other Philos than this one
            Q_ASSERT(Q_EVT_CAST(TableEvt)->philoId != me->id);
            status_ = QM_HANDLED();
            break;
        }
        //${AOs::Philo::SM::thinking::TEST}
        case TEST_SIG: {
            status_ = QM_HANDLED();
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    Q_UNUSED_PAR(me);
    return status_;
}

//${AOs::Philo::SM::hungry} ..................................................
//${AOs::Philo::SM::hungry}
static QState Philo_hungry_e(Philo * const me) {
    #ifdef QEVT_PAR_INIT
    TableEvt const *pe = Q_NEW(TableEvt, HUNGRY_SIG, me->id);
    #else
    TableEvt *pe = Q_NEW(TableEvt, HUNGRY_SIG);
    pe->philoId = me->id;
    #endif
    QACTIVE_POST(AO_Table, &pe->super, &me->super);
    return QM_ENTRY(&Philo_hungry_s);
}
//${AOs::Philo::SM::hungry}
static QState Philo_hungry(Philo * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Philo::SM::hungry::EAT}
        case EAT_SIG: {
            //${AOs::Philo::SM::hungry::EAT::[e->philoId==me->iid]}
            if (Q_EVT_CAST(TableEvt)->philoId == me->id) {
                static struct {
                    QMState const *target;
                    QActionHandler act[2];
                } const tatbl_ = { // tran-action table
                    &Philo_eating_s, // target state
                    {
                        Q_ACTION_CAST(&Philo_eating_e), // entry
                        Q_ACTION_NULL // zero terminator
                    }
                };
                status_ = QM_TRAN(&tatbl_);
            }
            else {
                status_ = QM_UNHANDLED();
            }
            break;
        }
        //${AOs::Philo::SM::hungry::DONE}
        case DONE_SIG: {
            // DONE must be for other Philos than this one
            Q_ASSERT(Q_EVT_CAST(TableEvt)->philoId != me->id);
            status_ = QM_HANDLED();
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

//${AOs::Philo::SM::eating} ..................................................
//${AOs::Philo::SM::eating}
static QState Philo_eating_e(Philo * const me) {
    QTimeEvt_armX(&me->timeEvt, eat_time(), 0U);
    return QM_ENTRY(&Philo_eating_s);
}
//${AOs::Philo::SM::eating}
static QState Philo_eating_x(Philo * const me) {
    (void)QTimeEvt_disarm(&me->timeEvt);

    #ifdef QEVT_PAR_INIT
    TableEvt const *pe = Q_NEW(TableEvt, DONE_SIG, me->id);
    #else
    TableEvt *pe = Q_NEW(TableEvt, DONE_SIG);
    pe->philoId = me->id;
    #endif
    QACTIVE_PUBLISH(&pe->super, Q_ACTIVE_UPCAST(me));
    return QM_EXIT(&Philo_eating_s);
}
//${AOs::Philo::SM::eating}
static QState Philo_eating(Philo * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Philo::SM::eating::TIMEOUT}
        case TIMEOUT_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[3];
            } const tatbl_ = { // tran-action table
                &Philo_thinking_s, // target state
                {
                    Q_ACTION_CAST(&Philo_eating_x), // exit
                    Q_ACTION_CAST(&Philo_thinking_e), // entry
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        //${AOs::Philo::SM::eating::EAT, DONE}
        case EAT_SIG: // intentionally fall through
        case DONE_SIG: {
            // EAT or DONE must be for other Philos than this one
            Q_ASSERT(Q_EVT_CAST(TableEvt)->philoId != me->id);
            status_ = QM_HANDLED();
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}
//$enddef${AOs::Philo} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
