//$file${.::cut_qmsm.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: qmsm.qm
// File:  ${.::cut_qmsm.c}
//
// This code has been generated by QM 7.0.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::cut_qmsm.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpc.h"          // QP/C framework
#include "cut_qmsm.h"     // Code Under Test (CUT)

Q_DEFINE_THIS_FILE

//$declare${SMs::TstSM} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${SMs::TstSM} ..............................................................
typedef struct TstSM {
// protected:
    QMsm super;

// private:
    uint8_t foo;

// public:

// private state histories
    QMState const *hist_s;
    QMState const *hist_s1;
    QMState const *hist_s2;
} TstSM;

extern TstSM TstSM_inst;

// protected:
static QState TstSM_initial(TstSM * const me, void const * const par);
static QState TstSM_s  (TstSM * const me, QEvt const * const e);
static QState TstSM_s_e(TstSM * const me);
static QState TstSM_s_x(TstSM * const me);
static QState TstSM_s_i(TstSM * const me);
static QMState const TstSM_s_s = {
    QM_STATE_NULL, // superstate (top)
    Q_STATE_CAST(&TstSM_s),
    Q_ACTION_CAST(&TstSM_s_e),
    Q_ACTION_CAST(&TstSM_s_x),
    Q_ACTION_CAST(&TstSM_s_i)
};
static QState TstSM_s1  (TstSM * const me, QEvt const * const e);
static QState TstSM_s1_e(TstSM * const me);
static QState TstSM_s1_x(TstSM * const me);
static QState TstSM_s1_i(TstSM * const me);
static QMState const TstSM_s1_s = {
    &TstSM_s_s, // superstate
    Q_STATE_CAST(&TstSM_s1),
    Q_ACTION_CAST(&TstSM_s1_e),
    Q_ACTION_CAST(&TstSM_s1_x),
    Q_ACTION_CAST(&TstSM_s1_i)
};
static QState TstSM_s11  (TstSM * const me, QEvt const * const e);
static QState TstSM_s11_e(TstSM * const me);
static QState TstSM_s11_x(TstSM * const me);
static QState TstSM_s11_i(TstSM * const me);
static QMState const TstSM_s11_s = {
    &TstSM_s1_s, // superstate
    Q_STATE_CAST(&TstSM_s11),
    Q_ACTION_CAST(&TstSM_s11_e),
    Q_ACTION_CAST(&TstSM_s11_x),
    Q_ACTION_CAST(&TstSM_s11_i)
};
static QState TstSM_s111  (TstSM * const me, QEvt const * const e);
static QState TstSM_s111_e(TstSM * const me);
static QState TstSM_s111_x(TstSM * const me);
static QMState const TstSM_s111_s = {
    &TstSM_s11_s, // superstate
    Q_STATE_CAST(&TstSM_s111),
    Q_ACTION_CAST(&TstSM_s111_e),
    Q_ACTION_CAST(&TstSM_s111_x),
    Q_ACTION_NULL  // no initial tran.
};
static QState TstSM_s112  (TstSM * const me, QEvt const * const e);
static QState TstSM_s112_e(TstSM * const me);
static QState TstSM_s112_x(TstSM * const me);
static QMState const TstSM_s112_s = {
    &TstSM_s11_s, // superstate
    Q_STATE_CAST(&TstSM_s112),
    Q_ACTION_CAST(&TstSM_s112_e),
    Q_ACTION_CAST(&TstSM_s112_x),
    Q_ACTION_NULL  // no initial tran.
};
static QState TstSM_s12  (TstSM * const me, QEvt const * const e);
static QState TstSM_s12_e(TstSM * const me);
static QState TstSM_s12_x(TstSM * const me);
static QMState const TstSM_s12_s = {
    &TstSM_s1_s, // superstate
    Q_STATE_CAST(&TstSM_s12),
    Q_ACTION_CAST(&TstSM_s12_e),
    Q_ACTION_CAST(&TstSM_s12_x),
    Q_ACTION_NULL  // no initial tran.
};
static QState TstSM_s2  (TstSM * const me, QEvt const * const e);
static QState TstSM_s2_e(TstSM * const me);
static QState TstSM_s2_x(TstSM * const me);
static QState TstSM_s2_i(TstSM * const me);
static QMState const TstSM_s2_s = {
    &TstSM_s_s, // superstate
    Q_STATE_CAST(&TstSM_s2),
    Q_ACTION_CAST(&TstSM_s2_e),
    Q_ACTION_CAST(&TstSM_s2_x),
    Q_ACTION_CAST(&TstSM_s2_i)
};
static QState TstSM_s21  (TstSM * const me, QEvt const * const e);
static QState TstSM_s21_e(TstSM * const me);
static QState TstSM_s21_x(TstSM * const me);
static QState TstSM_s21_i(TstSM * const me);
static QMState const TstSM_s21_s = {
    &TstSM_s2_s, // superstate
    Q_STATE_CAST(&TstSM_s21),
    Q_ACTION_CAST(&TstSM_s21_e),
    Q_ACTION_CAST(&TstSM_s21_x),
    Q_ACTION_CAST(&TstSM_s21_i)
};
static QState TstSM_s211  (TstSM * const me, QEvt const * const e);
static QState TstSM_s211_e(TstSM * const me);
static QState TstSM_s211_x(TstSM * const me);
static QMState const TstSM_s211_s = {
    &TstSM_s21_s, // superstate
    Q_STATE_CAST(&TstSM_s211),
    Q_ACTION_CAST(&TstSM_s211_e),
    Q_ACTION_CAST(&TstSM_s211_x),
    Q_ACTION_NULL  // no initial tran.
};
static QState TstSM_s212  (TstSM * const me, QEvt const * const e);
static QState TstSM_s212_e(TstSM * const me);
static QState TstSM_s212_x(TstSM * const me);
static QMState const TstSM_s212_s = {
    &TstSM_s21_s, // superstate
    Q_STATE_CAST(&TstSM_s212),
    Q_ACTION_CAST(&TstSM_s212_e),
    Q_ACTION_CAST(&TstSM_s212_x),
    Q_ACTION_NULL  // no initial tran.
};
static QState TstSM_s22  (TstSM * const me, QEvt const * const e);
static QState TstSM_s22_e(TstSM * const me);
static QState TstSM_s22_x(TstSM * const me);
static QMState const TstSM_s22_s = {
    &TstSM_s2_s, // superstate
    Q_STATE_CAST(&TstSM_s22),
    Q_ACTION_CAST(&TstSM_s22_e),
    Q_ACTION_CAST(&TstSM_s22_x),
    Q_ACTION_NULL  // no initial tran.
};
static QState TstSM_t  (TstSM * const me, QEvt const * const e);
static QState TstSM_t_e(TstSM * const me);
static QState TstSM_t_x(TstSM * const me);
static QMState const TstSM_t_s = {
    QM_STATE_NULL, // superstate (top)
    Q_STATE_CAST(&TstSM_t),
    Q_ACTION_CAST(&TstSM_t_e),
    Q_ACTION_CAST(&TstSM_t_x),
    Q_ACTION_NULL  // no initial tran.
};
//$enddecl${SMs::TstSM} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${Shared::the_sm} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Shared::the_sm} ..........................................................
QAsm * const the_sm = &TstSM_inst.super.super;
//$enddef${Shared::the_sm} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${Shared::TstSM_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Shared::TstSM_ctor} ......................................................
void TstSM_ctor(void) {
    TstSM *me = &TstSM_inst;
    QMsm_ctor(&me->super, Q_STATE_CAST(&TstSM_initial));
}
//$enddef${Shared::TstSM_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${Shared::TstSM_isIn} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Shared::TstSM_isIn} ......................................................
bool TstSM_isIn(uint32_t const state_num) {
    QMsm * const me = &TstSM_inst.super;
    bool stat = false;
    switch (state_num) {
    case 0:
        stat = QASM_IS_IN(me, Q_STATE_CAST(&TstSM_s));
        break;
    case 1:
        stat = QASM_IS_IN(me, Q_STATE_CAST(&TstSM_s1));
        break;
    case 11:
        stat = QASM_IS_IN(me, Q_STATE_CAST(&TstSM_s11));
        break;
    case 111:
        stat = QASM_IS_IN(me, Q_STATE_CAST(&TstSM_s111));
        break;
    case 112:
        stat = QASM_IS_IN(me, Q_STATE_CAST(&TstSM_s112));
        break;
    case 12:
        stat = QASM_IS_IN(me, Q_STATE_CAST(&TstSM_s12));
        break;
    case 2:
        stat = QASM_IS_IN(me, Q_STATE_CAST(&TstSM_s2));
        break;
    case 21:
        stat = QASM_IS_IN(me, Q_STATE_CAST(&TstSM_s21));
        break;
    case 211:
        stat = QASM_IS_IN(me, Q_STATE_CAST(&TstSM_s211));
        break;
    case 212:
        stat = QASM_IS_IN(me, Q_STATE_CAST(&TstSM_s212));
        break;
    case 22:
        stat = QASM_IS_IN(me, Q_STATE_CAST(&TstSM_s22));
        break;
    default:
        Q_ERROR();
    }
    return stat;
}
//$enddef${Shared::TstSM_isIn} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${SMs::TstSM} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${SMs::TstSM} ..............................................................
TstSM TstSM_inst;

//${SMs::TstSM::SM} ..........................................................
static QState TstSM_initial(TstSM * const me, void const * const par) {
    //${SMs::TstSM::SM::initial}
    Q_UNUSED_PAR(par);
    me->foo = 0U;
    BSP_display("top-INIT;");

    QS_SIG_DICTIONARY(A_SIG, (void *)0);
    QS_SIG_DICTIONARY(B_SIG, (void *)0);
    QS_SIG_DICTIONARY(C_SIG, (void *)0);
    QS_SIG_DICTIONARY(D_SIG, (void *)0);
    QS_SIG_DICTIONARY(E_SIG, (void *)0);
    QS_SIG_DICTIONARY(F_SIG, (void *)0);
    QS_SIG_DICTIONARY(G_SIG, (void *)0);
    QS_SIG_DICTIONARY(H_SIG, (void *)0);
    QS_SIG_DICTIONARY(I_SIG, (void *)0);
    // state history attributes
    me->hist_s = &TstSM_s1_s;
    me->hist_s1 = &TstSM_s11_s;
    me->hist_s2 = &TstSM_s211_s;

    QS_FUN_DICTIONARY(&TstSM_s);
    QS_FUN_DICTIONARY(&TstSM_s1);
    QS_FUN_DICTIONARY(&TstSM_s11);
    QS_FUN_DICTIONARY(&TstSM_s111);
    QS_FUN_DICTIONARY(&TstSM_s112);
    QS_FUN_DICTIONARY(&TstSM_s12);
    QS_FUN_DICTIONARY(&TstSM_s2);
    QS_FUN_DICTIONARY(&TstSM_s21);
    QS_FUN_DICTIONARY(&TstSM_s211);
    QS_FUN_DICTIONARY(&TstSM_s212);
    QS_FUN_DICTIONARY(&TstSM_s22);
    QS_FUN_DICTIONARY(&TstSM_t);

    static struct {
        QMState const *target;
        QActionHandler act[4];
    } const tatbl_ = { // tran-action table
        &TstSM_s2_s, // target state
        {
            Q_ACTION_CAST(&TstSM_s_e), // entry
            Q_ACTION_CAST(&TstSM_s2_e), // entry
            Q_ACTION_CAST(&TstSM_s2_i), // initial tran.
            Q_ACTION_NULL // zero terminator
        }
    };
    return QM_TRAN_INIT(&tatbl_);
}

//${SMs::TstSM::SM::s} .......................................................
//${SMs::TstSM::SM::s}
static QState TstSM_s_e(TstSM * const me) {
    BSP_display("s-ENTRY;");
    Q_UNUSED_PAR(me);
    return QM_ENTRY(&TstSM_s_s);
}
//${SMs::TstSM::SM::s}
static QState TstSM_s_x(TstSM * const me) {
    BSP_display("s-EXIT;");
    // save shallow history
    me->hist_s =
        QMsm_childStateObj(Q_MSM_UPCAST(me), &TstSM_s_s);
    return QM_EXIT(&TstSM_s_s);
}
//${SMs::TstSM::SM::s::initial}
static QState TstSM_s_i(TstSM * const me) {
    //${SMs::TstSM::SM::s::initial}
    BSP_display("s-INIT;");
    static struct {
        QMState const *target;
        QActionHandler act[3];
    } const tatbl_ = { // tran-action table
        &TstSM_s1_s, // target state
        {
            Q_ACTION_CAST(&TstSM_s1_e), // entry
            Q_ACTION_CAST(&TstSM_s1_i), // initial tran.
            Q_ACTION_NULL // zero terminator
        }
    };
    return QM_TRAN_INIT(&tatbl_);
}
//${SMs::TstSM::SM::s}
static QState TstSM_s(TstSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${SMs::TstSM::SM::s::E}
        case E_SIG: {
            BSP_display("s-E;");
            static struct {
                QMState const *target;
                QActionHandler act[4];
            } const tatbl_ = { // tran-action table
                &TstSM_s11_s, // target state
                {
                    Q_ACTION_CAST(&TstSM_s1_e), // entry
                    Q_ACTION_CAST(&TstSM_s11_e), // entry
                    Q_ACTION_CAST(&TstSM_s11_i), // initial tran.
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        //${SMs::TstSM::SM::s::I}
        case I_SIG: {
            BSP_display("s-I;");
            status_ = QM_HANDLED();
            break;
        }
        //${SMs::TstSM::SM::s::C}
        case C_SIG: {
            BSP_display("s-C;");
            static struct {
                QMState const *target;
                QActionHandler act[3];
            } const tatbl_ = { // tran-action table
                &TstSM_t_s, // target state
                {
                    Q_ACTION_CAST(&TstSM_s_x), // exit
                    Q_ACTION_CAST(&TstSM_t_e), // entry
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

//${SMs::TstSM::SM::s::s1} ...................................................
//${SMs::TstSM::SM::s::s1}
static QState TstSM_s1_e(TstSM * const me) {
    BSP_display("s1-ENTRY;");
    Q_UNUSED_PAR(me);
    return QM_ENTRY(&TstSM_s1_s);
}
//${SMs::TstSM::SM::s::s1}
static QState TstSM_s1_x(TstSM * const me) {
    BSP_display("s1-EXIT;");
    // save shallow history
    me->hist_s1 =
        QMsm_childStateObj(Q_MSM_UPCAST(me), &TstSM_s1_s);
    return QM_EXIT(&TstSM_s1_s);
}
//${SMs::TstSM::SM::s::s1::initial}
static QState TstSM_s1_i(TstSM * const me) {
    //${SMs::TstSM::SM::s::s1::initial}
    BSP_display("s1-INIT;");
    static struct {
        QMState const *target;
        QActionHandler act[3];
    } const tatbl_ = { // tran-action table
        &TstSM_s111_s, // target state
        {
            Q_ACTION_CAST(&TstSM_s11_e), // entry
            Q_ACTION_CAST(&TstSM_s111_e), // entry
            Q_ACTION_NULL // zero terminator
        }
    };
    return QM_TRAN_INIT(&tatbl_);
}
//${SMs::TstSM::SM::s::s1}
static QState TstSM_s1(TstSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${SMs::TstSM::SM::s::s1::E}
        case E_SIG: {
            BSP_display("s1-E;");
            static struct {
                QMState const *target;
                QActionHandler act[2];
            } const tatbl_ = { // tran-action table
                &TstSM_s12_s, // target state
                {
                    Q_ACTION_CAST(&TstSM_s12_e), // entry
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        //${SMs::TstSM::SM::s::s1::F}
        case F_SIG: {
            BSP_display("s1-F;");
            static struct {
                QMState const *target;
                QActionHandler act[5];
            } const tatbl_ = { // tran-action table
                &TstSM_s21_s, // target state
                {
                    Q_ACTION_CAST(&TstSM_s1_x), // exit
                    Q_ACTION_CAST(&TstSM_s2_e), // entry
                    Q_ACTION_CAST(&TstSM_s21_e), // entry
                    Q_ACTION_CAST(&TstSM_s21_i), // initial tran.
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        //${SMs::TstSM::SM::s::s1::I}
        case I_SIG: {
            //${SMs::TstSM::SM::s::s1::I::[me->foo]}
            if (me->foo) {
                me->foo = 0U;
                BSP_display("s1-I;");
                status_ = QM_HANDLED();
            }
            else {
                status_ = QM_UNHANDLED();
            }
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

//${SMs::TstSM::SM::s::s1::s11} ..............................................
//${SMs::TstSM::SM::s::s1::s11}
static QState TstSM_s11_e(TstSM * const me) {
    BSP_display("s11-ENTRY;");
    Q_UNUSED_PAR(me);
    return QM_ENTRY(&TstSM_s11_s);
}
//${SMs::TstSM::SM::s::s1::s11}
static QState TstSM_s11_x(TstSM * const me) {
    BSP_display("s11-EXIT;");
    (void)me; // unused parameter
    return QM_EXIT(&TstSM_s11_s);
}
//${SMs::TstSM::SM::s::s1::s11::initial}
static QState TstSM_s11_i(TstSM * const me) {
    //${SMs::TstSM::SM::s::s1::s11::initial}
    BSP_display("s11-INIT;");
    static struct {
        QMState const *target;
        QActionHandler act[2];
    } const tatbl_ = { // tran-action table
        &TstSM_s111_s, // target state
        {
            Q_ACTION_CAST(&TstSM_s111_e), // entry
            Q_ACTION_NULL // zero terminator
        }
    };
    return QM_TRAN_INIT(&tatbl_);
}
//${SMs::TstSM::SM::s::s1::s11}
static QState TstSM_s11(TstSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${SMs::TstSM::SM::s::s1::s11::A}
        case A_SIG: {
            BSP_display("s11-A;");
            static struct {
                QMState const *target;
                QActionHandler act[4];
            } const tatbl_ = { // tran-action table
                &TstSM_s11_s, // target state
                {
                    Q_ACTION_CAST(&TstSM_s11_x), // exit
                    Q_ACTION_CAST(&TstSM_s11_e), // entry
                    Q_ACTION_CAST(&TstSM_s11_i), // initial tran.
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        //${SMs::TstSM::SM::s::s1::s11::B}
        case B_SIG: {
            BSP_display("s11-B;");
            static struct {
                QMState const *target;
                QActionHandler act[2];
            } const tatbl_ = { // tran-action table
                &TstSM_s111_s, // target state
                {
                    Q_ACTION_CAST(&TstSM_s111_e), // entry
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        //${SMs::TstSM::SM::s::s1::s11::D}
        case D_SIG: {
            //${SMs::TstSM::SM::s::s1::s11::D::[!me->foo]}
            if (!me->foo) {
                me->foo = 1U;
                BSP_display("s11-D;");
                static struct {
                    QMState const *target;
                    QActionHandler act[3];
                } const tatbl_ = { // tran-action table
                    &TstSM_s1_s, // target state
                    {
                        Q_ACTION_CAST(&TstSM_s11_x), // exit
                        Q_ACTION_CAST(&TstSM_s1_i), // initial tran.
                        Q_ACTION_NULL // zero terminator
                    }
                };
                status_ = QM_TRAN(&tatbl_);
            }
            else {
                status_ = QM_UNHANDLED();
            }
            break;
        }
        //${SMs::TstSM::SM::s::s1::s11::G}
        case G_SIG: {
            BSP_display("s11-G->H*-s2;");
            static struct {
                QMState const *target;
                QActionHandler act[4];
            } const tatbl_ = { // tran-action table
                &TstSM_s2_s, // target state
                {
                    Q_ACTION_CAST(&TstSM_s11_x), // exit
                    Q_ACTION_CAST(&TstSM_s1_x), // exit
                    Q_ACTION_CAST(&TstSM_s2_e), // entry
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN_HIST(me->hist_s2, &tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

//${SMs::TstSM::SM::s::s1::s11::s111} ........................................
//${SMs::TstSM::SM::s::s1::s11::s111}
static QState TstSM_s111_e(TstSM * const me) {
    BSP_display("s111-ENTRY;");
    Q_UNUSED_PAR(me);
    return QM_ENTRY(&TstSM_s111_s);
}
//${SMs::TstSM::SM::s::s1::s11::s111}
static QState TstSM_s111_x(TstSM * const me) {
    BSP_display("s111-EXIT;");
    (void)me; // unused parameter
    return QM_EXIT(&TstSM_s111_s);
}
//${SMs::TstSM::SM::s::s1::s11::s111}
static QState TstSM_s111(TstSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${SMs::TstSM::SM::s::s1::s11::s111::C}
        case C_SIG: {
            BSP_display("s111-C;");
            static struct {
                QMState const *target;
                QActionHandler act[3];
            } const tatbl_ = { // tran-action table
                &TstSM_s112_s, // target state
                {
                    Q_ACTION_CAST(&TstSM_s111_x), // exit
                    Q_ACTION_CAST(&TstSM_s112_e), // entry
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

//${SMs::TstSM::SM::s::s1::s11::s112} ........................................
//${SMs::TstSM::SM::s::s1::s11::s112}
static QState TstSM_s112_e(TstSM * const me) {
    BSP_display("s112-ENTRY;");
    Q_UNUSED_PAR(me);
    return QM_ENTRY(&TstSM_s112_s);
}
//${SMs::TstSM::SM::s::s1::s11::s112}
static QState TstSM_s112_x(TstSM * const me) {
    BSP_display("s112-EXIT;");
    (void)me; // unused parameter
    return QM_EXIT(&TstSM_s112_s);
}
//${SMs::TstSM::SM::s::s1::s11::s112}
static QState TstSM_s112(TstSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${SMs::TstSM::SM::s::s1::s11::s112::H}
        case H_SIG: {
            BSP_display("s112-H;");
            static struct {
                QMState const *target;
                QActionHandler act[5];
            } const tatbl_ = { // tran-action table
                &TstSM_s_s, // target state
                {
                    Q_ACTION_CAST(&TstSM_s112_x), // exit
                    Q_ACTION_CAST(&TstSM_s11_x), // exit
                    Q_ACTION_CAST(&TstSM_s1_x), // exit
                    Q_ACTION_CAST(&TstSM_s_i), // initial tran.
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

//${SMs::TstSM::SM::s::s1::s12} ..............................................
//${SMs::TstSM::SM::s::s1::s12}
static QState TstSM_s12_e(TstSM * const me) {
    BSP_display("s12-ENTRY;");
    Q_UNUSED_PAR(me);
    return QM_ENTRY(&TstSM_s12_s);
}
//${SMs::TstSM::SM::s::s1::s12}
static QState TstSM_s12_x(TstSM * const me) {
    BSP_display("s12-EXIT;");
    (void)me; // unused parameter
    return QM_EXIT(&TstSM_s12_s);
}
//${SMs::TstSM::SM::s::s1::s12}
static QState TstSM_s12(TstSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    Q_UNUSED_PAR(me);
    return status_;
}

//${SMs::TstSM::SM::s::s2} ...................................................
//${SMs::TstSM::SM::s::s2}
static QState TstSM_s2_e(TstSM * const me) {
    BSP_display("s2-ENTRY;");
    Q_UNUSED_PAR(me);
    return QM_ENTRY(&TstSM_s2_s);
}
//${SMs::TstSM::SM::s::s2}
static QState TstSM_s2_x(TstSM * const me) {
    BSP_display("s2-EXIT;");
    // save deep history
    me->hist_s2 = QMsm_stateObj(Q_MSM_UPCAST(me));
    return QM_EXIT(&TstSM_s2_s);
}
//${SMs::TstSM::SM::s::s2::initial}
static QState TstSM_s2_i(TstSM * const me) {
    //${SMs::TstSM::SM::s::s2::initial}
    BSP_display("s2-INIT;");
    static struct {
        QMState const *target;
        QActionHandler act[3];
    } const tatbl_ = { // tran-action table
        &TstSM_s211_s, // target state
        {
            Q_ACTION_CAST(&TstSM_s21_e), // entry
            Q_ACTION_CAST(&TstSM_s211_e), // entry
            Q_ACTION_NULL // zero terminator
        }
    };
    return QM_TRAN_INIT(&tatbl_);
}
//${SMs::TstSM::SM::s::s2}
static QState TstSM_s2(TstSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${SMs::TstSM::SM::s::s2::E}
        case E_SIG: {
            BSP_display("s2-E;");
            static struct {
                QMState const *target;
                QActionHandler act[2];
            } const tatbl_ = { // tran-action table
                &TstSM_s22_s, // target state
                {
                    Q_ACTION_CAST(&TstSM_s22_e), // entry
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        //${SMs::TstSM::SM::s::s2::F}
        case F_SIG: {
            BSP_display("s2-F;");
            static struct {
                QMState const *target;
                QActionHandler act[5];
            } const tatbl_ = { // tran-action table
                &TstSM_s11_s, // target state
                {
                    Q_ACTION_CAST(&TstSM_s2_x), // exit
                    Q_ACTION_CAST(&TstSM_s1_e), // entry
                    Q_ACTION_CAST(&TstSM_s11_e), // entry
                    Q_ACTION_CAST(&TstSM_s11_i), // initial tran.
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        //${SMs::TstSM::SM::s::s2::I}
        case I_SIG: {
            //${SMs::TstSM::SM::s::s2::I::[me->foo]}
            if (me->foo) {
                me->foo = 0U;
                BSP_display("s2-I;");
                status_ = QM_HANDLED();
            }
            else {
                status_ = QM_UNHANDLED();
            }
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

//${SMs::TstSM::SM::s::s2::s21} ..............................................
//${SMs::TstSM::SM::s::s2::s21}
static QState TstSM_s21_e(TstSM * const me) {
    BSP_display("s21-ENTRY;");
    Q_UNUSED_PAR(me);
    return QM_ENTRY(&TstSM_s21_s);
}
//${SMs::TstSM::SM::s::s2::s21}
static QState TstSM_s21_x(TstSM * const me) {
    BSP_display("s21-EXIT;");
    (void)me; // unused parameter
    return QM_EXIT(&TstSM_s21_s);
}
//${SMs::TstSM::SM::s::s2::s21::initial}
static QState TstSM_s21_i(TstSM * const me) {
    //${SMs::TstSM::SM::s::s2::s21::initial}
    BSP_display("s21-INIT;");
    static struct {
        QMState const *target;
        QActionHandler act[2];
    } const tatbl_ = { // tran-action table
        &TstSM_s211_s, // target state
        {
            Q_ACTION_CAST(&TstSM_s211_e), // entry
            Q_ACTION_NULL // zero terminator
        }
    };
    return QM_TRAN_INIT(&tatbl_);
}
//${SMs::TstSM::SM::s::s2::s21}
static QState TstSM_s21(TstSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${SMs::TstSM::SM::s::s2::s21::A}
        case A_SIG: {
            BSP_display("s21-A;");
            static struct {
                QMState const *target;
                QActionHandler act[4];
            } const tatbl_ = { // tran-action table
                &TstSM_s21_s, // target state
                {
                    Q_ACTION_CAST(&TstSM_s21_x), // exit
                    Q_ACTION_CAST(&TstSM_s21_e), // entry
                    Q_ACTION_CAST(&TstSM_s21_i), // initial tran.
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        //${SMs::TstSM::SM::s::s2::s21::B}
        case B_SIG: {
            BSP_display("s21-B;");
            static struct {
                QMState const *target;
                QActionHandler act[2];
            } const tatbl_ = { // tran-action table
                &TstSM_s211_s, // target state
                {
                    Q_ACTION_CAST(&TstSM_s211_e), // entry
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        //${SMs::TstSM::SM::s::s2::s21::D}
        case D_SIG: {
            //${SMs::TstSM::SM::s::s2::s21::D::[!me->foo]}
            if (!me->foo) {
                me->foo = 1U;
                BSP_display("s21-D;");
                static struct {
                    QMState const *target;
                    QActionHandler act[3];
                } const tatbl_ = { // tran-action table
                    &TstSM_s2_s, // target state
                    {
                        Q_ACTION_CAST(&TstSM_s21_x), // exit
                        Q_ACTION_CAST(&TstSM_s2_i), // initial tran.
                        Q_ACTION_NULL // zero terminator
                    }
                };
                status_ = QM_TRAN(&tatbl_);
            }
            else {
                status_ = QM_UNHANDLED();
            }
            break;
        }
        //${SMs::TstSM::SM::s::s2::s21::G}
        case G_SIG: {
            BSP_display("s21-G->H*-s1;");
            static struct {
                QMState const *target;
                QActionHandler act[4];
            } const tatbl_ = { // tran-action table
                &TstSM_s1_s, // target state
                {
                    Q_ACTION_CAST(&TstSM_s21_x), // exit
                    Q_ACTION_CAST(&TstSM_s2_x), // exit
                    Q_ACTION_CAST(&TstSM_s1_e), // entry
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN_HIST(me->hist_s1, &tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

//${SMs::TstSM::SM::s::s2::s21::s211} ........................................
//${SMs::TstSM::SM::s::s2::s21::s211}
static QState TstSM_s211_e(TstSM * const me) {
    BSP_display("s211-ENTRY;");
    Q_UNUSED_PAR(me);
    return QM_ENTRY(&TstSM_s211_s);
}
//${SMs::TstSM::SM::s::s2::s21::s211}
static QState TstSM_s211_x(TstSM * const me) {
    BSP_display("s211-EXIT;");
    (void)me; // unused parameter
    return QM_EXIT(&TstSM_s211_s);
}
//${SMs::TstSM::SM::s::s2::s21::s211}
static QState TstSM_s211(TstSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${SMs::TstSM::SM::s::s2::s21::s211::C}
        case C_SIG: {
            BSP_display("s211-C;");
            static struct {
                QMState const *target;
                QActionHandler act[3];
            } const tatbl_ = { // tran-action table
                &TstSM_s212_s, // target state
                {
                    Q_ACTION_CAST(&TstSM_s211_x), // exit
                    Q_ACTION_CAST(&TstSM_s212_e), // entry
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

//${SMs::TstSM::SM::s::s2::s21::s212} ........................................
//${SMs::TstSM::SM::s::s2::s21::s212}
static QState TstSM_s212_e(TstSM * const me) {
    BSP_display("s212-ENTRY;");
    Q_UNUSED_PAR(me);
    return QM_ENTRY(&TstSM_s212_s);
}
//${SMs::TstSM::SM::s::s2::s21::s212}
static QState TstSM_s212_x(TstSM * const me) {
    BSP_display("s212-EXIT;");
    (void)me; // unused parameter
    return QM_EXIT(&TstSM_s212_s);
}
//${SMs::TstSM::SM::s::s2::s21::s212}
static QState TstSM_s212(TstSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${SMs::TstSM::SM::s::s2::s21::s212::H}
        case H_SIG: {
            BSP_display("s212-H;");
            static struct {
                QMState const *target;
                QActionHandler act[5];
            } const tatbl_ = { // tran-action table
                &TstSM_s_s, // target state
                {
                    Q_ACTION_CAST(&TstSM_s212_x), // exit
                    Q_ACTION_CAST(&TstSM_s21_x), // exit
                    Q_ACTION_CAST(&TstSM_s2_x), // exit
                    Q_ACTION_CAST(&TstSM_s_i), // initial tran.
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

//${SMs::TstSM::SM::s::s2::s22} ..............................................
//${SMs::TstSM::SM::s::s2::s22}
static QState TstSM_s22_e(TstSM * const me) {
    BSP_display("s22-ENTRY;");
    Q_UNUSED_PAR(me);
    return QM_ENTRY(&TstSM_s22_s);
}
//${SMs::TstSM::SM::s::s2::s22}
static QState TstSM_s22_x(TstSM * const me) {
    BSP_display("s22-EXIT;");
    (void)me; // unused parameter
    return QM_EXIT(&TstSM_s22_s);
}
//${SMs::TstSM::SM::s::s2::s22}
static QState TstSM_s22(TstSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    Q_UNUSED_PAR(me);
    return status_;
}

//${SMs::TstSM::SM::t} .......................................................
//${SMs::TstSM::SM::t}
static QState TstSM_t_e(TstSM * const me) {
    BSP_display("t-ENTRY;");
    Q_UNUSED_PAR(me);
    return QM_ENTRY(&TstSM_t_s);
}
//${SMs::TstSM::SM::t}
static QState TstSM_t_x(TstSM * const me) {
    BSP_display("t-EXIT;");
    (void)me; // unused parameter
    return QM_EXIT(&TstSM_t_s);
}
//${SMs::TstSM::SM::t}
static QState TstSM_t(TstSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${SMs::TstSM::SM::t::C}
        case C_SIG: {
            BSP_display("t-C->H-s;");
            static struct {
                QMState const *target;
                QActionHandler act[3];
            } const tatbl_ = { // tran-action table
                &TstSM_s_s, // target state
                {
                    Q_ACTION_CAST(&TstSM_t_x), // exit
                    Q_ACTION_CAST(&TstSM_s_e), // entry
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN_HIST(me->hist_s, &tatbl_);
            break;
        }
        //${SMs::TstSM::SM::t::E}
        case E_SIG: {
            BSP_display("t-E->H*-s2;");
            static struct {
                QMState const *target;
                QActionHandler act[4];
            } const tatbl_ = { // tran-action table
                &TstSM_s2_s, // target state
                {
                    Q_ACTION_CAST(&TstSM_t_x), // exit
                    Q_ACTION_CAST(&TstSM_s_e), // entry
                    Q_ACTION_CAST(&TstSM_s2_e), // entry
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN_HIST(me->hist_s2, &tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}
//$enddef${SMs::TstSM} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
