//$file${.::tstsm_sf.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: tstsm.qm
// File:  ${.::tstsm_sf.h}
//
// This code has been generated by QM 7.0.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// This generated code is covered by the following QP license:
// License #    : LicenseRef-QL-commercial
// Issued to    : SafeQP/C Licensee
// Framework(s) : qpc
// Support ends : 2025-12-31
// Copyright (C) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                    Q u a n t u m  L e a P s
//                    ------------------------
//                    Modern Embedded Software
//
// SPDX-License-Identifier: LicenseRef-QL-commercial
//
// This software is licensed under the terms of the Quantum Leaps commercial
// licenses. Please contact Quantum Leaps for more information about the
// available licensing options.
//
// RESTRICTIONS
// You may NOT :
// (a) redistribute, encumber, sell, rent, lease, sublicense, or otherwise
//     transfer rights in this software,
// (b) remove or alter any trademark, logo, copyright or other proprietary
//     notices, legends, symbols or labels present in this software,
// (c) plagiarize this software to sidestep the licensing obligations.
//
// Quantum Leaps contact information :
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::tstsm_sf.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef TSTSM_SF_H_
#define TSTSM_SF_H_

//$declare${Shared_SF} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Shared_SF::TstSM0_ctor} ..................................................
void TstSM0_ctor(void);

//${Shared_SF::TstSM1_ctor} ..................................................
void TstSM1_ctor(void);

//${Shared_SF::TstSM2_ctor} ..................................................
void TstSM2_ctor(void);

//${Shared_SF::TstSM3_ctor} ..................................................
void TstSM3_ctor(void);

//${Shared_SF::TstSM4_ctor} ..................................................
void TstSM4_ctor(void);

//${Shared_SF::TstSM5_ctor} ..................................................
void TstSM5_ctor(void);

//${Shared_SF::the_TstSM0} ...................................................
extern QAsm * const the_TstSM0;

//${Shared_SF::the_TstSM1} ...................................................
extern QAsm * const the_TstSM1;

//${Shared_SF::the_TstSM2} ...................................................
extern QAsm * const the_TstSM2;

//${Shared_SF::the_TstSM3} ...................................................
extern QAsm * const the_TstSM3;

//${Shared_SF::the_TstSM4} ...................................................
extern QAsm * const the_TstSM4;

//${Shared_SF::the_TstSM5} ...................................................
extern QAsm * const the_TstSM5;

//${Shared_SF::TstSM5_isIn} ..................................................
bool TstSM5_isIn(uint32_t const state_num);

//${Shared_SF::TstSM5_child} .................................................
QStateHandler TstSM5_child(uint32_t const state_num);
//$enddecl${Shared_SF} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#endif // TSTSM_SF_H_
