//$file${.::tstsm_sf.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: tstsm.qm
// File:  ${.::tstsm_sf.c}
//
// This code has been generated by QM 7.0.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// This generated code is covered by the following QP license:
// License #    : LicenseRef-QL-commercial
// Issued to    : SafeQP/C Licensee
// Framework(s) : qpc
// Support ends : 2025-12-31
// Copyright (C) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                    Q u a n t u m  L e a P s
//                    ------------------------
//                    Modern Embedded Software
//
// SPDX-License-Identifier: LicenseRef-QL-commercial
//
// This software is licensed under the terms of the Quantum Leaps commercial
// licenses. Please contact Quantum Leaps for more information about the
// available licensing options.
//
// RESTRICTIONS
// You may NOT :
// (a) redistribute, encumber, sell, rent, lease, sublicense, or otherwise
//     transfer rights in this software,
// (b) remove or alter any trademark, logo, copyright or other proprietary
//     notices, legends, symbols or labels present in this software,
// (c) plagiarize this software to sidestep the licensing obligations.
//
// Quantum Leaps contact information :
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::tstsm_sf.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpc.h"       // QP/C framework
#include "tstsm.h"     // TstSM state machine
#include "tstsm_sf.h"  // TstSM state machine for Safety Functions

Q_DEFINE_THIS_FILE

//$declare${SFs} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${SFs::TstSM0} .............................................................
typedef struct TstSM0 {
// protected:
    QMsm super;

// public:
} TstSM0;

extern TstSM0 TstSM0_inst;

//${SFs::TstSM1} .............................................................
typedef struct TstSM1 {
// protected:
    QMsm super;

// public:
} TstSM1;

extern TstSM1 TstSM1_inst;

// protected:
static QState TstSM1_initial(TstSM1 * const me, void const * const par);
static QState TstSM1_s1  (TstSM1 * const me, QEvt const * const e);
static QMState const TstSM1_s1_s = {
    QM_STATE_NULL, // superstate (top)
    Q_STATE_CAST(&TstSM1_s1),
    Q_ACTION_NULL, // no entry action
    Q_ACTION_NULL, // no exit action
    Q_ACTION_NULL  // no initial tran.
};

//${SFs::TstSM2} .............................................................
typedef struct TstSM2 {
// protected:
    QMsm super;

// public:
} TstSM2;

extern TstSM2 TstSM2_inst;

// protected:
static QState TstSM2_initial(TstSM2 * const me, void const * const par);
static QState TstSM2_s1  (TstSM2 * const me, QEvt const * const e);
static QMState const TstSM2_s1_s = {
    QM_STATE_NULL, // superstate (top)
    Q_STATE_CAST(&TstSM2_s1),
    Q_ACTION_NULL, // no entry action
    Q_ACTION_NULL, // no exit action
    Q_ACTION_NULL  // no initial tran.
};

//${SFs::TstSM3} .............................................................
typedef struct TstSM3 {
// protected:
    QMsm super;

// public:
} TstSM3;

extern TstSM3 TstSM3_inst;

// protected:
static QState TstSM3_initial(TstSM3 * const me, void const * const par);
static QState TstSM3_s1  (TstSM3 * const me, QEvt const * const e);
static QMState const TstSM3_s1_s = {
    QM_STATE_NULL, // superstate (top)
    Q_STATE_CAST(&TstSM3_s1),
    Q_ACTION_NULL, // no entry action
    Q_ACTION_NULL, // no exit action
    Q_ACTION_NULL  // no initial tran.
};

//${SFs::TstSM4} .............................................................
typedef struct TstSM4 {
// protected:
    QMsm super;

// public:
} TstSM4;

extern TstSM4 TstSM4_inst;

// protected:
static QState TstSM4_initial(TstSM4 * const me, void const * const par);
static QState TstSM4_s1  (TstSM4 * const me, QEvt const * const e);
static QState TstSM4_s1_e(TstSM4 * const me);
static QState TstSM4_s1_x(TstSM4 * const me);
static QState TstSM4_s1_i(TstSM4 * const me);
static QMState const TstSM4_s1_s = {
    QM_STATE_NULL, // superstate (top)
    Q_STATE_CAST(&TstSM4_s1),
    Q_ACTION_CAST(&TstSM4_s1_e),
    Q_ACTION_CAST(&TstSM4_s1_x),
    Q_ACTION_CAST(&TstSM4_s1_i)
};
static QState TstSM4_s2  (TstSM4 * const me, QEvt const * const e);
static QState TstSM4_s2_e(TstSM4 * const me);
static QState TstSM4_s2_x(TstSM4 * const me);
static QState TstSM4_s2_i(TstSM4 * const me);
static QMState const TstSM4_s2_s = {
    &TstSM4_s1_s, // superstate
    Q_STATE_CAST(&TstSM4_s2),
    Q_ACTION_CAST(&TstSM4_s2_e),
    Q_ACTION_CAST(&TstSM4_s2_x),
    Q_ACTION_CAST(&TstSM4_s2_i)
};
static QState TstSM4_s3  (TstSM4 * const me, QEvt const * const e);
static QState TstSM4_s3_e(TstSM4 * const me);
static QState TstSM4_s3_x(TstSM4 * const me);
static QState TstSM4_s3_i(TstSM4 * const me);
static QMState const TstSM4_s3_s = {
    &TstSM4_s2_s, // superstate
    Q_STATE_CAST(&TstSM4_s3),
    Q_ACTION_CAST(&TstSM4_s3_e),
    Q_ACTION_CAST(&TstSM4_s3_x),
    Q_ACTION_CAST(&TstSM4_s3_i)
};
static QState TstSM4_s4  (TstSM4 * const me, QEvt const * const e);
static QState TstSM4_s4_e(TstSM4 * const me);
static QState TstSM4_s4_x(TstSM4 * const me);
static QState TstSM4_s4_i(TstSM4 * const me);
static QMState const TstSM4_s4_s = {
    &TstSM4_s3_s, // superstate
    Q_STATE_CAST(&TstSM4_s4),
    Q_ACTION_CAST(&TstSM4_s4_e),
    Q_ACTION_CAST(&TstSM4_s4_x),
    Q_ACTION_CAST(&TstSM4_s4_i)
};
static QState TstSM4_s5  (TstSM4 * const me, QEvt const * const e);
static QState TstSM4_s5_e(TstSM4 * const me);
static QState TstSM4_s5_x(TstSM4 * const me);
static QState TstSM4_s5_i(TstSM4 * const me);
static QMState const TstSM4_s5_s = {
    &TstSM4_s4_s, // superstate
    Q_STATE_CAST(&TstSM4_s5),
    Q_ACTION_CAST(&TstSM4_s5_e),
    Q_ACTION_CAST(&TstSM4_s5_x),
    Q_ACTION_CAST(&TstSM4_s5_i)
};
static QState TstSM4_s6  (TstSM4 * const me, QEvt const * const e);
static QState TstSM4_s6_e(TstSM4 * const me);
static QState TstSM4_s6_x(TstSM4 * const me);
static QState TstSM4_s6_i(TstSM4 * const me);
static QMState const TstSM4_s6_s = {
    &TstSM4_s5_s, // superstate
    Q_STATE_CAST(&TstSM4_s6),
    Q_ACTION_CAST(&TstSM4_s6_e),
    Q_ACTION_CAST(&TstSM4_s6_x),
    Q_ACTION_CAST(&TstSM4_s6_i)
};
static QState TstSM4_s7  (TstSM4 * const me, QEvt const * const e);
static QState TstSM4_s7_e(TstSM4 * const me);
static QState TstSM4_s7_x(TstSM4 * const me);
static QState TstSM4_s7_i(TstSM4 * const me);
static QMState const TstSM4_s7_s = {
    &TstSM4_s6_s, // superstate
    Q_STATE_CAST(&TstSM4_s7),
    Q_ACTION_CAST(&TstSM4_s7_e),
    Q_ACTION_CAST(&TstSM4_s7_x),
    Q_ACTION_CAST(&TstSM4_s7_i)
};
static QState TstSM4_s8  (TstSM4 * const me, QEvt const * const e);
static QState TstSM4_s8_e(TstSM4 * const me);
static QState TstSM4_s8_x(TstSM4 * const me);
static QMState const TstSM4_s8_s = {
    &TstSM4_s7_s, // superstate
    Q_STATE_CAST(&TstSM4_s8),
    Q_ACTION_CAST(&TstSM4_s8_e),
    Q_ACTION_CAST(&TstSM4_s8_x),
    Q_ACTION_NULL  // no initial tran.
};

//${SFs::TstSM5} .............................................................
typedef struct TstSM5 {
// protected:
    QMsm super;

// public:

// private state histories
    QMState const *hist_s1;
    QMState const *hist_t1;
} TstSM5;

extern TstSM5 TstSM5_inst;

// protected:
static QState TstSM5_initial(TstSM5 * const me, void const * const par);
static QState TstSM5_s1  (TstSM5 * const me, QEvt const * const e);
static QState TstSM5_s1_e(TstSM5 * const me);
static QState TstSM5_s1_x(TstSM5 * const me);
static QState TstSM5_s1_i(TstSM5 * const me);
static QMState const TstSM5_s1_s = {
    QM_STATE_NULL, // superstate (top)
    Q_STATE_CAST(&TstSM5_s1),
    Q_ACTION_CAST(&TstSM5_s1_e),
    Q_ACTION_CAST(&TstSM5_s1_x),
    Q_ACTION_CAST(&TstSM5_s1_i)
};
static QState TstSM5_s2  (TstSM5 * const me, QEvt const * const e);
static QState TstSM5_s2_e(TstSM5 * const me);
static QState TstSM5_s2_x(TstSM5 * const me);
static QState TstSM5_s2_i(TstSM5 * const me);
static QMState const TstSM5_s2_s = {
    &TstSM5_s1_s, // superstate
    Q_STATE_CAST(&TstSM5_s2),
    Q_ACTION_CAST(&TstSM5_s2_e),
    Q_ACTION_CAST(&TstSM5_s2_x),
    Q_ACTION_CAST(&TstSM5_s2_i)
};
static QState TstSM5_s3  (TstSM5 * const me, QEvt const * const e);
static QState TstSM5_s3_e(TstSM5 * const me);
static QState TstSM5_s3_x(TstSM5 * const me);
static QState TstSM5_s3_i(TstSM5 * const me);
static QMState const TstSM5_s3_s = {
    &TstSM5_s2_s, // superstate
    Q_STATE_CAST(&TstSM5_s3),
    Q_ACTION_CAST(&TstSM5_s3_e),
    Q_ACTION_CAST(&TstSM5_s3_x),
    Q_ACTION_CAST(&TstSM5_s3_i)
};
static QState TstSM5_s4  (TstSM5 * const me, QEvt const * const e);
static QState TstSM5_s4_e(TstSM5 * const me);
static QState TstSM5_s4_x(TstSM5 * const me);
static QState TstSM5_s4_i(TstSM5 * const me);
static QMState const TstSM5_s4_s = {
    &TstSM5_s3_s, // superstate
    Q_STATE_CAST(&TstSM5_s4),
    Q_ACTION_CAST(&TstSM5_s4_e),
    Q_ACTION_CAST(&TstSM5_s4_x),
    Q_ACTION_CAST(&TstSM5_s4_i)
};
static QState TstSM5_s5  (TstSM5 * const me, QEvt const * const e);
static QState TstSM5_s5_e(TstSM5 * const me);
static QState TstSM5_s5_x(TstSM5 * const me);
static QState TstSM5_s5_i(TstSM5 * const me);
static QMState const TstSM5_s5_s = {
    &TstSM5_s4_s, // superstate
    Q_STATE_CAST(&TstSM5_s5),
    Q_ACTION_CAST(&TstSM5_s5_e),
    Q_ACTION_CAST(&TstSM5_s5_x),
    Q_ACTION_CAST(&TstSM5_s5_i)
};
static QState TstSM5_s6  (TstSM5 * const me, QEvt const * const e);
static QState TstSM5_s6_e(TstSM5 * const me);
static QState TstSM5_s6_x(TstSM5 * const me);
static QState TstSM5_s6_i(TstSM5 * const me);
static QMState const TstSM5_s6_s = {
    &TstSM5_s5_s, // superstate
    Q_STATE_CAST(&TstSM5_s6),
    Q_ACTION_CAST(&TstSM5_s6_e),
    Q_ACTION_CAST(&TstSM5_s6_x),
    Q_ACTION_CAST(&TstSM5_s6_i)
};
static QState TstSM5_s7  (TstSM5 * const me, QEvt const * const e);
static QState TstSM5_s7_e(TstSM5 * const me);
static QState TstSM5_s7_x(TstSM5 * const me);
static QState TstSM5_s7_i(TstSM5 * const me);
static QMState const TstSM5_s7_s = {
    &TstSM5_s6_s, // superstate
    Q_STATE_CAST(&TstSM5_s7),
    Q_ACTION_CAST(&TstSM5_s7_e),
    Q_ACTION_CAST(&TstSM5_s7_x),
    Q_ACTION_CAST(&TstSM5_s7_i)
};
static QState TstSM5_s8  (TstSM5 * const me, QEvt const * const e);
static QState TstSM5_s8_e(TstSM5 * const me);
static QState TstSM5_s8_x(TstSM5 * const me);
static QMState const TstSM5_s8_s = {
    &TstSM5_s7_s, // superstate
    Q_STATE_CAST(&TstSM5_s8),
    Q_ACTION_CAST(&TstSM5_s8_e),
    Q_ACTION_CAST(&TstSM5_s8_x),
    Q_ACTION_NULL  // no initial tran.
};
static QState TstSM5_t1  (TstSM5 * const me, QEvt const * const e);
static QState TstSM5_t1_e(TstSM5 * const me);
static QState TstSM5_t1_x(TstSM5 * const me);
static QMState const TstSM5_t1_s = {
    QM_STATE_NULL, // superstate (top)
    Q_STATE_CAST(&TstSM5_t1),
    Q_ACTION_CAST(&TstSM5_t1_e),
    Q_ACTION_CAST(&TstSM5_t1_x),
    Q_ACTION_NULL  // no initial tran.
};
static QState TstSM5_t2  (TstSM5 * const me, QEvt const * const e);
static QState TstSM5_t2_e(TstSM5 * const me);
static QState TstSM5_t2_x(TstSM5 * const me);
static QMState const TstSM5_t2_s = {
    &TstSM5_t1_s, // superstate
    Q_STATE_CAST(&TstSM5_t2),
    Q_ACTION_CAST(&TstSM5_t2_e),
    Q_ACTION_CAST(&TstSM5_t2_x),
    Q_ACTION_NULL  // no initial tran.
};
static QState TstSM5_t3  (TstSM5 * const me, QEvt const * const e);
static QState TstSM5_t3_e(TstSM5 * const me);
static QState TstSM5_t3_x(TstSM5 * const me);
static QMState const TstSM5_t3_s = {
    &TstSM5_t2_s, // superstate
    Q_STATE_CAST(&TstSM5_t3),
    Q_ACTION_CAST(&TstSM5_t3_e),
    Q_ACTION_CAST(&TstSM5_t3_x),
    Q_ACTION_NULL  // no initial tran.
};
static QState TstSM5_t4  (TstSM5 * const me, QEvt const * const e);
static QState TstSM5_t4_e(TstSM5 * const me);
static QState TstSM5_t4_x(TstSM5 * const me);
static QMState const TstSM5_t4_s = {
    &TstSM5_t3_s, // superstate
    Q_STATE_CAST(&TstSM5_t4),
    Q_ACTION_CAST(&TstSM5_t4_e),
    Q_ACTION_CAST(&TstSM5_t4_x),
    Q_ACTION_NULL  // no initial tran.
};
static QState TstSM5_t5  (TstSM5 * const me, QEvt const * const e);
static QState TstSM5_t5_e(TstSM5 * const me);
static QState TstSM5_t5_x(TstSM5 * const me);
static QMState const TstSM5_t5_s = {
    &TstSM5_t4_s, // superstate
    Q_STATE_CAST(&TstSM5_t5),
    Q_ACTION_CAST(&TstSM5_t5_e),
    Q_ACTION_CAST(&TstSM5_t5_x),
    Q_ACTION_NULL  // no initial tran.
};
static QState TstSM5_t6  (TstSM5 * const me, QEvt const * const e);
static QState TstSM5_t6_e(TstSM5 * const me);
static QState TstSM5_t6_x(TstSM5 * const me);
static QMState const TstSM5_t6_s = {
    &TstSM5_t5_s, // superstate
    Q_STATE_CAST(&TstSM5_t6),
    Q_ACTION_CAST(&TstSM5_t6_e),
    Q_ACTION_CAST(&TstSM5_t6_x),
    Q_ACTION_NULL  // no initial tran.
};
static QState TstSM5_t7  (TstSM5 * const me, QEvt const * const e);
static QState TstSM5_t7_e(TstSM5 * const me);
static QState TstSM5_t7_x(TstSM5 * const me);
static QMState const TstSM5_t7_s = {
    &TstSM5_t6_s, // superstate
    Q_STATE_CAST(&TstSM5_t7),
    Q_ACTION_CAST(&TstSM5_t7_e),
    Q_ACTION_CAST(&TstSM5_t7_x),
    Q_ACTION_NULL  // no initial tran.
};
static QState TstSM5_t8  (TstSM5 * const me, QEvt const * const e);
static QState TstSM5_t8_e(TstSM5 * const me);
static QState TstSM5_t8_x(TstSM5 * const me);
static QState TstSM5_t8_i(TstSM5 * const me);
static QMState const TstSM5_t8_s = {
    &TstSM5_t7_s, // superstate
    Q_STATE_CAST(&TstSM5_t8),
    Q_ACTION_CAST(&TstSM5_t8_e),
    Q_ACTION_CAST(&TstSM5_t8_x),
    Q_ACTION_CAST(&TstSM5_t8_i)
};
static QState TstSM5_t9  (TstSM5 * const me, QEvt const * const e);
static QState TstSM5_t9_x(TstSM5 * const me);
static QMState const TstSM5_t9_s = {
    &TstSM5_t8_s, // superstate
    Q_STATE_CAST(&TstSM5_t9),
    Q_ACTION_NULL, // no entry action
    Q_ACTION_CAST(&TstSM5_t9_x),
    Q_ACTION_NULL  // no initial tran.
};
//$enddecl${SFs} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${Shared_SF} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Shared_SF::TstSM0_ctor} ..................................................
void TstSM0_ctor(void) {
    TstSM0 *me = &TstSM0_inst;
    QMsm_ctor(&me->super, Q_STATE_CAST(0));
}

//${Shared_SF::TstSM1_ctor} ..................................................
void TstSM1_ctor(void) {
    TstSM1 *me = &TstSM1_inst;
    QMsm_ctor(&me->super, Q_STATE_CAST(&TstSM1_initial));
    me->super.super.state.obj = (QMState *)1234; // corrupt the state
}

//${Shared_SF::TstSM2_ctor} ..................................................
void TstSM2_ctor(void) {
    TstSM2 *me = &TstSM2_inst;
    QMsm_ctor(&me->super, Q_STATE_CAST(&TstSM2_initial));
}

//${Shared_SF::TstSM3_ctor} ..................................................
void TstSM3_ctor(void) {
    TstSM3 *me = &TstSM3_inst;
    QMsm_ctor(&me->super, Q_STATE_CAST(&TstSM3_initial));
}

//${Shared_SF::TstSM4_ctor} ..................................................
void TstSM4_ctor(void) {
    TstSM4 *me = &TstSM4_inst;
    QMsm_ctor(&me->super, Q_STATE_CAST(&TstSM4_initial));
}

//${Shared_SF::TstSM5_ctor} ..................................................
void TstSM5_ctor(void) {
    TstSM5 *me = &TstSM5_inst;
    QMsm_ctor(&me->super, Q_STATE_CAST(&TstSM5_initial));
}

//${Shared_SF::the_TstSM0} ...................................................
QAsm * const the_TstSM0 = &TstSM0_inst.super.super;

//${Shared_SF::the_TstSM1} ...................................................
QAsm * const the_TstSM1 = &TstSM1_inst.super.super;

//${Shared_SF::the_TstSM2} ...................................................
QAsm * const the_TstSM2 = &TstSM2_inst.super.super;

//${Shared_SF::the_TstSM3} ...................................................
QAsm * const the_TstSM3 = &TstSM3_inst.super.super;

//${Shared_SF::the_TstSM4} ...................................................
QAsm * const the_TstSM4 = &TstSM4_inst.super.super;

//${Shared_SF::the_TstSM5} ...................................................
QAsm * const the_TstSM5 = &TstSM5_inst.super.super;

//${Shared_SF::TstSM5_isIn} ..................................................
bool TstSM5_isIn(uint32_t const state_num) {
    bool stat = false;
    switch (state_num) {
    case 1:
        stat = QASM_IS_IN(the_TstSM5, Q_STATE_CAST(&TstSM5_s1));
        break;
    case 2:
        stat = QASM_IS_IN(the_TstSM5, Q_STATE_CAST(&TstSM5_s2));
        break;
    case 3:
        stat = QASM_IS_IN(the_TstSM5, Q_STATE_CAST(&TstSM5_s3));
        break;
    case 4:
        stat = QASM_IS_IN(the_TstSM5, Q_STATE_CAST(&TstSM5_s4));
        break;
    default:
        Q_ERROR();
    }
    return stat;
}

//${Shared_SF::TstSM5_child} .................................................
QStateHandler TstSM5_child(uint32_t const state_num) {
    QMState const *state;
    QMsm *me = (QMsm *)the_TstSM5;
    switch (state_num) {
    case 1:
        state = QMsm_childStateObj(me, &TstSM5_s1_s);
        break;
    case 2:
        state = QMsm_childStateObj(me, &TstSM5_s2_s);
        break;
    case 3:
        state = QMsm_childStateObj(me, &TstSM5_s3_s);
        break;
    case 4:
        state = QMsm_childStateObj(me, &TstSM5_s4_s);
        break;
    default:
        Q_ERROR();
    }
    return state->stateHandler;
}
//$enddef${Shared_SF} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${SFs} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${SFs::TstSM0} .............................................................
TstSM0 TstSM0_inst;

//${SFs::TstSM1} .............................................................
TstSM1 TstSM1_inst;

//${SFs::TstSM1::SM} .........................................................
static QState TstSM1_initial(TstSM1 * const me, void const * const par) {
    //${SFs::TstSM1::SM::initial}
    Q_UNUSED_PAR(par);

    QS_FUN_DICTIONARY(&TstSM1_s1);

    static QMTranActTable const tatbl_ = { // tran-action table
        &TstSM1_s1_s, // target state
        {
            Q_ACTION_NULL // zero terminator
        }
    };
    return QM_TRAN_INIT(&tatbl_);
}

//${SFs::TstSM1::SM::s1} .....................................................
//${SFs::TstSM1::SM::s1}
static QState TstSM1_s1(TstSM1 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    Q_UNUSED_PAR(me);
    return status_;
}

//${SFs::TstSM2} .............................................................
TstSM2 TstSM2_inst;

//${SFs::TstSM2::SM} .........................................................
static QState TstSM2_initial(TstSM2 * const me, void const * const par) {
    //${SFs::TstSM2::SM::initial}
    Q_UNUSED_PAR(par);
    return QM_TRAN(0); // initial tran. to NULL

    QS_FUN_DICTIONARY(&TstSM2_s1);

    static QMTranActTable const tatbl_ = { // tran-action table
        &TstSM2_s1_s, // target state
        {
            Q_ACTION_NULL // zero terminator
        }
    };
    return QM_TRAN_INIT(&tatbl_);
}

//${SFs::TstSM2::SM::s1} .....................................................
//${SFs::TstSM2::SM::s1}
static QState TstSM2_s1(TstSM2 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    Q_UNUSED_PAR(me);
    return status_;
}

//${SFs::TstSM3} .............................................................
TstSM3 TstSM3_inst;

//${SFs::TstSM3::SM} .........................................................
static QState TstSM3_initial(TstSM3 * const me, void const * const par) {
    //${SFs::TstSM3::SM::initial}
    Q_UNUSED_PAR(par);
    return QM_TRAN_INIT((struct QMTranActTable *)0); // NULL tran. table

    QS_FUN_DICTIONARY(&TstSM3_s1);

    static QMTranActTable const tatbl_ = { // tran-action table
        &TstSM3_s1_s, // target state
        {
            Q_ACTION_NULL // zero terminator
        }
    };
    return QM_TRAN_INIT(&tatbl_);
}

//${SFs::TstSM3::SM::s1} .....................................................
//${SFs::TstSM3::SM::s1}
static QState TstSM3_s1(TstSM3 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    Q_UNUSED_PAR(me);
    return status_;
}

//${SFs::TstSM4} .............................................................
TstSM4 TstSM4_inst;

//${SFs::TstSM4::SM} .........................................................
static QState TstSM4_initial(TstSM4 * const me, void const * const par) {
    //${SFs::TstSM4::SM::initial}
    Q_UNUSED_PAR(par);

    QS_FUN_DICTIONARY(&TstSM4_s1);
    QS_FUN_DICTIONARY(&TstSM4_s2);
    QS_FUN_DICTIONARY(&TstSM4_s3);
    QS_FUN_DICTIONARY(&TstSM4_s4);
    QS_FUN_DICTIONARY(&TstSM4_s5);
    QS_FUN_DICTIONARY(&TstSM4_s6);
    QS_FUN_DICTIONARY(&TstSM4_s7);
    QS_FUN_DICTIONARY(&TstSM4_s8);

    static struct {
        QMState const *target;
        QActionHandler act[3];
    } const tatbl_ = { // tran-action table
        &TstSM4_s1_s, // target state
        {
            Q_ACTION_CAST(&TstSM4_s1_e), // entry
            Q_ACTION_CAST(&TstSM4_s1_i), // initial tran.
            Q_ACTION_NULL // zero terminator
        }
    };
    return QM_TRAN_INIT(&tatbl_);
}

//${SFs::TstSM4::SM::s1} .....................................................
//${SFs::TstSM4::SM::s1}
static QState TstSM4_s1_e(TstSM4 * const me) {
    //
    Q_UNUSED_PAR(me);
    return QM_ENTRY(&TstSM4_s1_s);
}
//${SFs::TstSM4::SM::s1}
static QState TstSM4_s1_x(TstSM4 * const me) {
    //
    (void)me; // unused parameter
    return QM_EXIT(&TstSM4_s1_s);
}
//${SFs::TstSM4::SM::s1::initial}
static QState TstSM4_s1_i(TstSM4 * const me) {
    //${SFs::TstSM4::SM::s1::initial}
    static struct {
        QMState const *target;
        QActionHandler act[3];
    } const tatbl_ = { // tran-action table
        &TstSM4_s2_s, // target state
        {
            Q_ACTION_CAST(&TstSM4_s2_e), // entry
            Q_ACTION_CAST(&TstSM4_s2_i), // initial tran.
            Q_ACTION_NULL // zero terminator
        }
    };
    return QM_TRAN_INIT(&tatbl_);
}
//${SFs::TstSM4::SM::s1}
static QState TstSM4_s1(TstSM4 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    Q_UNUSED_PAR(me);
    return status_;
}

//${SFs::TstSM4::SM::s1::s2} .................................................
//${SFs::TstSM4::SM::s1::s2}
static QState TstSM4_s2_e(TstSM4 * const me) {
    //
    Q_UNUSED_PAR(me);
    return QM_ENTRY(&TstSM4_s2_s);
}
//${SFs::TstSM4::SM::s1::s2}
static QState TstSM4_s2_x(TstSM4 * const me) {
    //
    (void)me; // unused parameter
    return QM_EXIT(&TstSM4_s2_s);
}
//${SFs::TstSM4::SM::s1::s2::initial}
static QState TstSM4_s2_i(TstSM4 * const me) {
    //${SFs::TstSM4::SM::s1::s2::initial}
    static struct {
        QMState const *target;
        QActionHandler act[3];
    } const tatbl_ = { // tran-action table
        &TstSM4_s3_s, // target state
        {
            Q_ACTION_CAST(&TstSM4_s3_e), // entry
            Q_ACTION_CAST(&TstSM4_s3_i), // initial tran.
            Q_ACTION_NULL // zero terminator
        }
    };
    return QM_TRAN_INIT(&tatbl_);
}
//${SFs::TstSM4::SM::s1::s2}
static QState TstSM4_s2(TstSM4 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    Q_UNUSED_PAR(me);
    return status_;
}

//${SFs::TstSM4::SM::s1::s2::s3} .............................................
//${SFs::TstSM4::SM::s1::s2::s3}
static QState TstSM4_s3_e(TstSM4 * const me) {
    //
    Q_UNUSED_PAR(me);
    return QM_ENTRY(&TstSM4_s3_s);
}
//${SFs::TstSM4::SM::s1::s2::s3}
static QState TstSM4_s3_x(TstSM4 * const me) {
    //
    (void)me; // unused parameter
    return QM_EXIT(&TstSM4_s3_s);
}
//${SFs::TstSM4::SM::s1::s2::s3::initial}
static QState TstSM4_s3_i(TstSM4 * const me) {
    //${SFs::TstSM4::SM::s1::s2::s3::initial}
    static struct {
        QMState const *target;
        QActionHandler act[3];
    } const tatbl_ = { // tran-action table
        &TstSM4_s4_s, // target state
        {
            Q_ACTION_CAST(&TstSM4_s4_e), // entry
            Q_ACTION_CAST(&TstSM4_s4_i), // initial tran.
            Q_ACTION_NULL // zero terminator
        }
    };
    return QM_TRAN_INIT(&tatbl_);
}
//${SFs::TstSM4::SM::s1::s2::s3}
static QState TstSM4_s3(TstSM4 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    Q_UNUSED_PAR(me);
    return status_;
}

//${SFs::TstSM4::SM::s1::s2::s3::s4} .........................................
//${SFs::TstSM4::SM::s1::s2::s3::s4}
static QState TstSM4_s4_e(TstSM4 * const me) {
    //
    Q_UNUSED_PAR(me);
    return QM_ENTRY(&TstSM4_s4_s);
}
//${SFs::TstSM4::SM::s1::s2::s3::s4}
static QState TstSM4_s4_x(TstSM4 * const me) {
    //
    (void)me; // unused parameter
    return QM_EXIT(&TstSM4_s4_s);
}
//${SFs::TstSM4::SM::s1::s2::s3::s4::initial}
static QState TstSM4_s4_i(TstSM4 * const me) {
    //${SFs::TstSM4::SM::s1::s2::s3::s4::initial}
    static struct {
        QMState const *target;
        QActionHandler act[3];
    } const tatbl_ = { // tran-action table
        &TstSM4_s5_s, // target state
        {
            Q_ACTION_CAST(&TstSM4_s5_e), // entry
            Q_ACTION_CAST(&TstSM4_s5_i), // initial tran.
            Q_ACTION_NULL // zero terminator
        }
    };
    return QM_TRAN_INIT(&tatbl_);
}
//${SFs::TstSM4::SM::s1::s2::s3::s4}
static QState TstSM4_s4(TstSM4 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    Q_UNUSED_PAR(me);
    return status_;
}

//${SFs::TstSM4::SM::s1::s2::s3::s4::s5} .....................................
//${SFs::TstSM4::SM::s1::s2::s3::s4::s5}
static QState TstSM4_s5_e(TstSM4 * const me) {
    //
    Q_UNUSED_PAR(me);
    return QM_ENTRY(&TstSM4_s5_s);
}
//${SFs::TstSM4::SM::s1::s2::s3::s4::s5}
static QState TstSM4_s5_x(TstSM4 * const me) {
    //
    (void)me; // unused parameter
    return QM_EXIT(&TstSM4_s5_s);
}
//${SFs::TstSM4::SM::s1::s2::s3::s4::s5::initial}
static QState TstSM4_s5_i(TstSM4 * const me) {
    //${SFs::TstSM4::SM::s1::s2::s3::s4::s5::initial}
    static struct {
        QMState const *target;
        QActionHandler act[3];
    } const tatbl_ = { // tran-action table
        &TstSM4_s6_s, // target state
        {
            Q_ACTION_CAST(&TstSM4_s6_e), // entry
            Q_ACTION_CAST(&TstSM4_s6_i), // initial tran.
            Q_ACTION_NULL // zero terminator
        }
    };
    return QM_TRAN_INIT(&tatbl_);
}
//${SFs::TstSM4::SM::s1::s2::s3::s4::s5}
static QState TstSM4_s5(TstSM4 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    Q_UNUSED_PAR(me);
    return status_;
}

//${SFs::TstSM4::SM::s1::s2::s3::s4::s5::s6} .................................
//${SFs::TstSM4::SM::s1::s2::s3::s4::s5::s6}
static QState TstSM4_s6_e(TstSM4 * const me) {
    //
    Q_UNUSED_PAR(me);
    return QM_ENTRY(&TstSM4_s6_s);
}
//${SFs::TstSM4::SM::s1::s2::s3::s4::s5::s6}
static QState TstSM4_s6_x(TstSM4 * const me) {
    //
    (void)me; // unused parameter
    return QM_EXIT(&TstSM4_s6_s);
}
//${SFs::TstSM4::SM::s1::s2::s3::s4::s5::s6::initial}
static QState TstSM4_s6_i(TstSM4 * const me) {
    //${SFs::TstSM4::SM::s1::s2::s3::s4::s5::s6::initial}
    static struct {
        QMState const *target;
        QActionHandler act[3];
    } const tatbl_ = { // tran-action table
        &TstSM4_s7_s, // target state
        {
            Q_ACTION_CAST(&TstSM4_s7_e), // entry
            Q_ACTION_CAST(&TstSM4_s7_i), // initial tran.
            Q_ACTION_NULL // zero terminator
        }
    };
    return QM_TRAN_INIT(&tatbl_);
}
//${SFs::TstSM4::SM::s1::s2::s3::s4::s5::s6}
static QState TstSM4_s6(TstSM4 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    Q_UNUSED_PAR(me);
    return status_;
}

//${SFs::TstSM4::SM::s1::s2::s3::s4::s5::s6::s7} .............................
//${SFs::TstSM4::SM::s1::s2::s3::s4::s5::s6::s7}
static QState TstSM4_s7_e(TstSM4 * const me) {
    //
    Q_UNUSED_PAR(me);
    return QM_ENTRY(&TstSM4_s7_s);
}
//${SFs::TstSM4::SM::s1::s2::s3::s4::s5::s6::s7}
static QState TstSM4_s7_x(TstSM4 * const me) {
    //
    (void)me; // unused parameter
    return QM_EXIT(&TstSM4_s7_s);
}
//${SFs::TstSM4::SM::s1::s2::s3::s4::s5::s6::s7::initial}
static QState TstSM4_s7_i(TstSM4 * const me) {
    //${SFs::TstSM4::SM::s1::s2::s3::s4::s5::s6::s7::initial}
    static struct {
        QMState const *target;
        QActionHandler act[2];
    } const tatbl_ = { // tran-action table
        &TstSM4_s8_s, // target state
        {
            Q_ACTION_CAST(&TstSM4_s8_e), // entry
            Q_ACTION_NULL // zero terminator
        }
    };
    return QM_TRAN_INIT(&tatbl_);
}
//${SFs::TstSM4::SM::s1::s2::s3::s4::s5::s6::s7}
static QState TstSM4_s7(TstSM4 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    Q_UNUSED_PAR(me);
    return status_;
}

//${SFs::TstSM4::SM::s1::s2::s3::s4::s5::s6::s7::s8} .........................
//${SFs::TstSM4::SM::s1::s2::s3::s4::s5::s6::s7::s8}
static QState TstSM4_s8_e(TstSM4 * const me) {
    //
    Q_UNUSED_PAR(me);
    return QM_ENTRY(&TstSM4_s8_s);
}
//${SFs::TstSM4::SM::s1::s2::s3::s4::s5::s6::s7::s8}
static QState TstSM4_s8_x(TstSM4 * const me) {
    //
    (void)me; // unused parameter
    return QM_EXIT(&TstSM4_s8_s);
}
//${SFs::TstSM4::SM::s1::s2::s3::s4::s5::s6::s7::s8}
static QState TstSM4_s8(TstSM4 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    Q_UNUSED_PAR(me);
    return status_;
}

//${SFs::TstSM5} .............................................................
TstSM5 TstSM5_inst;

//${SFs::TstSM5::SM} .........................................................
static QState TstSM5_initial(TstSM5 * const me, void const * const par) {
    //${SFs::TstSM5::SM::initial}
    Q_UNUSED_PAR(par);

    QS_OBJ_DICTIONARY(&TstSM2_inst);
    // state history attributes
    me->hist_s1 = &TstSM5_s8_s;
    me->hist_t1 = &TstSM5_t9_s;

    QS_FUN_DICTIONARY(&TstSM5_s1);
    QS_FUN_DICTIONARY(&TstSM5_s2);
    QS_FUN_DICTIONARY(&TstSM5_s3);
    QS_FUN_DICTIONARY(&TstSM5_s4);
    QS_FUN_DICTIONARY(&TstSM5_s5);
    QS_FUN_DICTIONARY(&TstSM5_s6);
    QS_FUN_DICTIONARY(&TstSM5_s7);
    QS_FUN_DICTIONARY(&TstSM5_s8);
    QS_FUN_DICTIONARY(&TstSM5_t1);
    QS_FUN_DICTIONARY(&TstSM5_t2);
    QS_FUN_DICTIONARY(&TstSM5_t3);
    QS_FUN_DICTIONARY(&TstSM5_t4);
    QS_FUN_DICTIONARY(&TstSM5_t5);
    QS_FUN_DICTIONARY(&TstSM5_t6);
    QS_FUN_DICTIONARY(&TstSM5_t7);
    QS_FUN_DICTIONARY(&TstSM5_t8);
    QS_FUN_DICTIONARY(&TstSM5_t9);

    static struct {
        QMState const *target;
        QActionHandler act[8];
    } const tatbl_ = { // tran-action table
        &TstSM5_s6_s, // target state
        {
            Q_ACTION_CAST(&TstSM5_s1_e), // entry
            Q_ACTION_CAST(&TstSM5_s2_e), // entry
            Q_ACTION_CAST(&TstSM5_s3_e), // entry
            Q_ACTION_CAST(&TstSM5_s4_e), // entry
            Q_ACTION_CAST(&TstSM5_s5_e), // entry
            Q_ACTION_CAST(&TstSM5_s6_e), // entry
            Q_ACTION_CAST(&TstSM5_s6_i), // initial tran.
            Q_ACTION_NULL // zero terminator
        }
    };
    return QM_TRAN_INIT(&tatbl_);
}

//${SFs::TstSM5::SM::s1} .....................................................
//${SFs::TstSM5::SM::s1}
static QState TstSM5_s1_e(TstSM5 * const me) {
    //
    Q_UNUSED_PAR(me);
    return QM_ENTRY(&TstSM5_s1_s);
}
//${SFs::TstSM5::SM::s1}
static QState TstSM5_s1_x(TstSM5 * const me) {
    //
    // save deep history
    me->hist_s1 = QMsm_stateObj(Q_MSM_UPCAST(me));
    return QM_EXIT(&TstSM5_s1_s);
}
//${SFs::TstSM5::SM::s1::initial}
static QState TstSM5_s1_i(TstSM5 * const me) {
    //${SFs::TstSM5::SM::s1::initial}
    static struct {
        QMState const *target;
        QActionHandler act[3];
    } const tatbl_ = { // tran-action table
        &TstSM5_s2_s, // target state
        {
            Q_ACTION_CAST(&TstSM5_s2_e), // entry
            Q_ACTION_CAST(&TstSM5_s2_i), // initial tran.
            Q_ACTION_NULL // zero terminator
        }
    };
    return QM_TRAN_INIT(&tatbl_);
}
//${SFs::TstSM5::SM::s1}
static QState TstSM5_s1(TstSM5 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    Q_UNUSED_PAR(me);
    return status_;
}

//${SFs::TstSM5::SM::s1::s2} .................................................
//${SFs::TstSM5::SM::s1::s2}
static QState TstSM5_s2_e(TstSM5 * const me) {
    //
    Q_UNUSED_PAR(me);
    return QM_ENTRY(&TstSM5_s2_s);
}
//${SFs::TstSM5::SM::s1::s2}
static QState TstSM5_s2_x(TstSM5 * const me) {
    //
    (void)me; // unused parameter
    return QM_EXIT(&TstSM5_s2_s);
}
//${SFs::TstSM5::SM::s1::s2::initial}
static QState TstSM5_s2_i(TstSM5 * const me) {
    //${SFs::TstSM5::SM::s1::s2::initial}
    static struct {
        QMState const *target;
        QActionHandler act[3];
    } const tatbl_ = { // tran-action table
        &TstSM5_s3_s, // target state
        {
            Q_ACTION_CAST(&TstSM5_s3_e), // entry
            Q_ACTION_CAST(&TstSM5_s3_i), // initial tran.
            Q_ACTION_NULL // zero terminator
        }
    };
    return QM_TRAN_INIT(&tatbl_);
}
//${SFs::TstSM5::SM::s1::s2}
static QState TstSM5_s2(TstSM5 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    Q_UNUSED_PAR(me);
    return status_;
}

//${SFs::TstSM5::SM::s1::s2::s3} .............................................
//${SFs::TstSM5::SM::s1::s2::s3}
static QState TstSM5_s3_e(TstSM5 * const me) {
    //
    Q_UNUSED_PAR(me);
    return QM_ENTRY(&TstSM5_s3_s);
}
//${SFs::TstSM5::SM::s1::s2::s3}
static QState TstSM5_s3_x(TstSM5 * const me) {
    //
    (void)me; // unused parameter
    return QM_EXIT(&TstSM5_s3_s);
}
//${SFs::TstSM5::SM::s1::s2::s3::initial}
static QState TstSM5_s3_i(TstSM5 * const me) {
    //${SFs::TstSM5::SM::s1::s2::s3::initial}
    static struct {
        QMState const *target;
        QActionHandler act[3];
    } const tatbl_ = { // tran-action table
        &TstSM5_s4_s, // target state
        {
            Q_ACTION_CAST(&TstSM5_s4_e), // entry
            Q_ACTION_CAST(&TstSM5_s4_i), // initial tran.
            Q_ACTION_NULL // zero terminator
        }
    };
    return QM_TRAN_INIT(&tatbl_);
}
//${SFs::TstSM5::SM::s1::s2::s3}
static QState TstSM5_s3(TstSM5 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${SFs::TstSM5::SM::s1::s2::s3::A}
        case A_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[4];
            } const tatbl_ = { // tran-action table
                &TstSM5_s1_s, // target state
                {
                    Q_ACTION_CAST(&TstSM5_s3_x), // exit
                    Q_ACTION_CAST(&TstSM5_s2_x), // exit
                    Q_ACTION_CAST(&TstSM5_s1_i), // initial tran.
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        //${SFs::TstSM5::SM::s1::s2::s3::D}
        case D_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[9];
            } const tatbl_ = { // tran-action table
                &TstSM5_t5_s, // target state
                {
                    Q_ACTION_CAST(&TstSM5_s3_x), // exit
                    Q_ACTION_CAST(&TstSM5_s2_x), // exit
                    Q_ACTION_CAST(&TstSM5_s1_x), // exit
                    Q_ACTION_CAST(&TstSM5_t1_e), // entry
                    Q_ACTION_CAST(&TstSM5_t2_e), // entry
                    Q_ACTION_CAST(&TstSM5_t3_e), // entry
                    Q_ACTION_CAST(&TstSM5_t4_e), // entry
                    Q_ACTION_CAST(&TstSM5_t5_e), // entry
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

//${SFs::TstSM5::SM::s1::s2::s3::s4} .........................................
//${SFs::TstSM5::SM::s1::s2::s3::s4}
static QState TstSM5_s4_e(TstSM5 * const me) {
    //
    Q_UNUSED_PAR(me);
    return QM_ENTRY(&TstSM5_s4_s);
}
//${SFs::TstSM5::SM::s1::s2::s3::s4}
static QState TstSM5_s4_x(TstSM5 * const me) {
    //
    (void)me; // unused parameter
    return QM_EXIT(&TstSM5_s4_s);
}
//${SFs::TstSM5::SM::s1::s2::s3::s4::initial}
static QState TstSM5_s4_i(TstSM5 * const me) {
    //${SFs::TstSM5::SM::s1::s2::s3::s4::initial}
    static struct {
        QMState const *target;
        QActionHandler act[3];
    } const tatbl_ = { // tran-action table
        &TstSM5_s5_s, // target state
        {
            Q_ACTION_CAST(&TstSM5_s5_e), // entry
            Q_ACTION_CAST(&TstSM5_s5_i), // initial tran.
            Q_ACTION_NULL // zero terminator
        }
    };
    return QM_TRAN_INIT(&tatbl_);
}
//${SFs::TstSM5::SM::s1::s2::s3::s4}
static QState TstSM5_s4(TstSM5 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    Q_UNUSED_PAR(me);
    return status_;
}

//${SFs::TstSM5::SM::s1::s2::s3::s4::s5} .....................................
//${SFs::TstSM5::SM::s1::s2::s3::s4::s5}
static QState TstSM5_s5_e(TstSM5 * const me) {
    //
    Q_UNUSED_PAR(me);
    return QM_ENTRY(&TstSM5_s5_s);
}
//${SFs::TstSM5::SM::s1::s2::s3::s4::s5}
static QState TstSM5_s5_x(TstSM5 * const me) {
    //
    (void)me; // unused parameter
    return QM_EXIT(&TstSM5_s5_s);
}
//${SFs::TstSM5::SM::s1::s2::s3::s4::s5::initial}
static QState TstSM5_s5_i(TstSM5 * const me) {
    //${SFs::TstSM5::SM::s1::s2::s3::s4::s5::initial}
    static struct {
        QMState const *target;
        QActionHandler act[3];
    } const tatbl_ = { // tran-action table
        &TstSM5_s6_s, // target state
        {
            Q_ACTION_CAST(&TstSM5_s6_e), // entry
            Q_ACTION_CAST(&TstSM5_s6_i), // initial tran.
            Q_ACTION_NULL // zero terminator
        }
    };
    return QM_TRAN_INIT(&tatbl_);
}
//${SFs::TstSM5::SM::s1::s2::s3::s4::s5}
static QState TstSM5_s5(TstSM5 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    Q_UNUSED_PAR(me);
    return status_;
}

//${SFs::TstSM5::SM::s1::s2::s3::s4::s5::s6} .................................
//${SFs::TstSM5::SM::s1::s2::s3::s4::s5::s6}
static QState TstSM5_s6_e(TstSM5 * const me) {
    //
    Q_UNUSED_PAR(me);
    return QM_ENTRY(&TstSM5_s6_s);
}
//${SFs::TstSM5::SM::s1::s2::s3::s4::s5::s6}
static QState TstSM5_s6_x(TstSM5 * const me) {
    //
    (void)me; // unused parameter
    return QM_EXIT(&TstSM5_s6_s);
}
//${SFs::TstSM5::SM::s1::s2::s3::s4::s5::s6::initial}
static QState TstSM5_s6_i(TstSM5 * const me) {
    //${SFs::TstSM5::SM::s1::s2::s3::s4::s5::s6::initial}
    static struct {
        QMState const *target;
        QActionHandler act[3];
    } const tatbl_ = { // tran-action table
        &TstSM5_s7_s, // target state
        {
            Q_ACTION_CAST(&TstSM5_s7_e), // entry
            Q_ACTION_CAST(&TstSM5_s7_i), // initial tran.
            Q_ACTION_NULL // zero terminator
        }
    };
    return QM_TRAN_INIT(&tatbl_);
}
//${SFs::TstSM5::SM::s1::s2::s3::s4::s5::s6}
static QState TstSM5_s6(TstSM5 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    Q_UNUSED_PAR(me);
    return status_;
}

//${SFs::TstSM5::SM::s1::s2::s3::s4::s5::s6::s7} .............................
//${SFs::TstSM5::SM::s1::s2::s3::s4::s5::s6::s7}
static QState TstSM5_s7_e(TstSM5 * const me) {
    //
    Q_UNUSED_PAR(me);
    return QM_ENTRY(&TstSM5_s7_s);
}
//${SFs::TstSM5::SM::s1::s2::s3::s4::s5::s6::s7}
static QState TstSM5_s7_x(TstSM5 * const me) {
    //
    (void)me; // unused parameter
    return QM_EXIT(&TstSM5_s7_s);
}
//${SFs::TstSM5::SM::s1::s2::s3::s4::s5::s6::s7::initial}
static QState TstSM5_s7_i(TstSM5 * const me) {
    //${SFs::TstSM5::SM::s1::s2::s3::s4::s5::s6::s7::initial}
    static struct {
        QMState const *target;
        QActionHandler act[2];
    } const tatbl_ = { // tran-action table
        &TstSM5_s8_s, // target state
        {
            Q_ACTION_CAST(&TstSM5_s8_e), // entry
            Q_ACTION_NULL // zero terminator
        }
    };
    return QM_TRAN_INIT(&tatbl_);
}
//${SFs::TstSM5::SM::s1::s2::s3::s4::s5::s6::s7}
static QState TstSM5_s7(TstSM5 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${SFs::TstSM5::SM::s1::s2::s3::s4::s5::s6::s7::H}
        case H_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[9];
            } const tatbl_ = { // tran-action table
                &TstSM5_t1_s, // target state
                {
                    Q_ACTION_CAST(&TstSM5_s7_x), // exit
                    Q_ACTION_CAST(&TstSM5_s6_x), // exit
                    Q_ACTION_CAST(&TstSM5_s5_x), // exit
                    Q_ACTION_CAST(&TstSM5_s4_x), // exit
                    Q_ACTION_CAST(&TstSM5_s3_x), // exit
                    Q_ACTION_CAST(&TstSM5_s2_x), // exit
                    Q_ACTION_CAST(&TstSM5_s1_x), // exit
                    Q_ACTION_CAST(&TstSM5_t1_e), // entry
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN_HIST(me->hist_t1, &tatbl_);
            break;
        }
        //${SFs::TstSM5::SM::s1::s2::s3::s4::s5::s6::s7::C}
        case C_SIG: {
            return QM_TRAN((struct QMTranActTable *)0); // NULL tran. table
            static struct {
                QMState const *target;
                QActionHandler act[4];
            } const tatbl_ = { // tran-action table
                &TstSM5_s5_s, // target state
                {
                    Q_ACTION_CAST(&TstSM5_s7_x), // exit
                    Q_ACTION_CAST(&TstSM5_s6_x), // exit
                    Q_ACTION_CAST(&TstSM5_s5_i), // initial tran.
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

//${SFs::TstSM5::SM::s1::s2::s3::s4::s5::s6::s7::s8} .........................
//${SFs::TstSM5::SM::s1::s2::s3::s4::s5::s6::s7::s8}
static QState TstSM5_s8_e(TstSM5 * const me) {
    //
    Q_UNUSED_PAR(me);
    return QM_ENTRY(&TstSM5_s8_s);
}
//${SFs::TstSM5::SM::s1::s2::s3::s4::s5::s6::s7::s8}
static QState TstSM5_s8_x(TstSM5 * const me) {
    //
    (void)me; // unused parameter
    return QM_EXIT(&TstSM5_s8_s);
}
//${SFs::TstSM5::SM::s1::s2::s3::s4::s5::s6::s7::s8}
static QState TstSM5_s8(TstSM5 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${SFs::TstSM5::SM::s1::s2::s3::s4::s5::s6::s7::s8::B}
        case B_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[17];
            } const tatbl_ = { // tran-action table
                &TstSM5_t9_s, // target state
                {
                    Q_ACTION_CAST(&TstSM5_s8_x), // exit
                    Q_ACTION_CAST(&TstSM5_s7_x), // exit
                    Q_ACTION_CAST(&TstSM5_s6_x), // exit
                    Q_ACTION_CAST(&TstSM5_s5_x), // exit
                    Q_ACTION_CAST(&TstSM5_s4_x), // exit
                    Q_ACTION_CAST(&TstSM5_s3_x), // exit
                    Q_ACTION_CAST(&TstSM5_s2_x), // exit
                    Q_ACTION_CAST(&TstSM5_s1_x), // exit
                    Q_ACTION_CAST(&TstSM5_t1_e), // entry
                    Q_ACTION_CAST(&TstSM5_t2_e), // entry
                    Q_ACTION_CAST(&TstSM5_t3_e), // entry
                    Q_ACTION_CAST(&TstSM5_t4_e), // entry
                    Q_ACTION_CAST(&TstSM5_t5_e), // entry
                    Q_ACTION_CAST(&TstSM5_t6_e), // entry
                    Q_ACTION_CAST(&TstSM5_t7_e), // entry
                    Q_ACTION_CAST(&TstSM5_t8_e), // entry
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

//${SFs::TstSM5::SM::t1} .....................................................
//${SFs::TstSM5::SM::t1}
static QState TstSM5_t1_e(TstSM5 * const me) {
    //
    Q_UNUSED_PAR(me);
    return QM_ENTRY(&TstSM5_t1_s);
}
//${SFs::TstSM5::SM::t1}
static QState TstSM5_t1_x(TstSM5 * const me) {
    //
    // save shallow history
    me->hist_t1 =
        QMsm_childStateObj(Q_MSM_UPCAST(me), &TstSM5_t1_s);
    return QM_EXIT(&TstSM5_t1_s);
}
//${SFs::TstSM5::SM::t1}
static QState TstSM5_t1(TstSM5 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    Q_UNUSED_PAR(me);
    return status_;
}

//${SFs::TstSM5::SM::t1::t2} .................................................
//${SFs::TstSM5::SM::t1::t2}
static QState TstSM5_t2_e(TstSM5 * const me) {
    //
    Q_UNUSED_PAR(me);
    return QM_ENTRY(&TstSM5_t2_s);
}
//${SFs::TstSM5::SM::t1::t2}
static QState TstSM5_t2_x(TstSM5 * const me) {
    //
    (void)me; // unused parameter
    return QM_EXIT(&TstSM5_t2_s);
}
//${SFs::TstSM5::SM::t1::t2}
static QState TstSM5_t2(TstSM5 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    Q_UNUSED_PAR(me);
    return status_;
}

//${SFs::TstSM5::SM::t1::t2::t3} .............................................
//${SFs::TstSM5::SM::t1::t2::t3}
static QState TstSM5_t3_e(TstSM5 * const me) {
    //
    Q_UNUSED_PAR(me);
    return QM_ENTRY(&TstSM5_t3_s);
}
//${SFs::TstSM5::SM::t1::t2::t3}
static QState TstSM5_t3_x(TstSM5 * const me) {
    //
    (void)me; // unused parameter
    return QM_EXIT(&TstSM5_t3_s);
}
//${SFs::TstSM5::SM::t1::t2::t3}
static QState TstSM5_t3(TstSM5 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    Q_UNUSED_PAR(me);
    return status_;
}

//${SFs::TstSM5::SM::t1::t2::t3::t4} .........................................
//${SFs::TstSM5::SM::t1::t2::t3::t4}
static QState TstSM5_t4_e(TstSM5 * const me) {
    //
    Q_UNUSED_PAR(me);
    return QM_ENTRY(&TstSM5_t4_s);
}
//${SFs::TstSM5::SM::t1::t2::t3::t4}
static QState TstSM5_t4_x(TstSM5 * const me) {
    //
    (void)me; // unused parameter
    return QM_EXIT(&TstSM5_t4_s);
}
//${SFs::TstSM5::SM::t1::t2::t3::t4}
static QState TstSM5_t4(TstSM5 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${SFs::TstSM5::SM::t1::t2::t3::t4::D}
        case D_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[6];
            } const tatbl_ = { // tran-action table
                &TstSM5_t8_s, // target state
                {
                    Q_ACTION_CAST(&TstSM5_t5_e), // entry
                    Q_ACTION_CAST(&TstSM5_t6_e), // entry
                    Q_ACTION_CAST(&TstSM5_t7_e), // entry
                    Q_ACTION_CAST(&TstSM5_t8_e), // entry
                    Q_ACTION_CAST(&TstSM5_t8_i), // initial tran.
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

//${SFs::TstSM5::SM::t1::t2::t3::t4::t5} .....................................
//${SFs::TstSM5::SM::t1::t2::t3::t4::t5}
static QState TstSM5_t5_e(TstSM5 * const me) {
    //
    Q_UNUSED_PAR(me);
    return QM_ENTRY(&TstSM5_t5_s);
}
//${SFs::TstSM5::SM::t1::t2::t3::t4::t5}
static QState TstSM5_t5_x(TstSM5 * const me) {
    //
    (void)me; // unused parameter
    return QM_EXIT(&TstSM5_t5_s);
}
//${SFs::TstSM5::SM::t1::t2::t3::t4::t5}
static QState TstSM5_t5(TstSM5 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${SFs::TstSM5::SM::t1::t2::t3::t4::t5::H}
        case H_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[7];
            } const tatbl_ = { // tran-action table
                &TstSM5_s1_s, // target state
                {
                    Q_ACTION_CAST(&TstSM5_t5_x), // exit
                    Q_ACTION_CAST(&TstSM5_t4_x), // exit
                    Q_ACTION_CAST(&TstSM5_t3_x), // exit
                    Q_ACTION_CAST(&TstSM5_t2_x), // exit
                    Q_ACTION_CAST(&TstSM5_t1_x), // exit
                    Q_ACTION_CAST(&TstSM5_s1_e), // entry
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN_HIST(me->hist_s1, &tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

//${SFs::TstSM5::SM::t1::t2::t3::t4::t5::t6} .................................
//${SFs::TstSM5::SM::t1::t2::t3::t4::t5::t6}
static QState TstSM5_t6_e(TstSM5 * const me) {
    //
    Q_UNUSED_PAR(me);
    return QM_ENTRY(&TstSM5_t6_s);
}
//${SFs::TstSM5::SM::t1::t2::t3::t4::t5::t6}
static QState TstSM5_t6_x(TstSM5 * const me) {
    //
    (void)me; // unused parameter
    return QM_EXIT(&TstSM5_t6_s);
}
//${SFs::TstSM5::SM::t1::t2::t3::t4::t5::t6}
static QState TstSM5_t6(TstSM5 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    Q_UNUSED_PAR(me);
    return status_;
}

//${SFs::TstSM5::SM::t1::t2::t3::t4::t5::t6::t7} .............................
//${SFs::TstSM5::SM::t1::t2::t3::t4::t5::t6::t7}
static QState TstSM5_t7_e(TstSM5 * const me) {
    //
    Q_UNUSED_PAR(me);
    return QM_ENTRY(&TstSM5_t7_s);
}
//${SFs::TstSM5::SM::t1::t2::t3::t4::t5::t6::t7}
static QState TstSM5_t7_x(TstSM5 * const me) {
    //
    (void)me; // unused parameter
    return QM_EXIT(&TstSM5_t7_s);
}
//${SFs::TstSM5::SM::t1::t2::t3::t4::t5::t6::t7}
static QState TstSM5_t7(TstSM5 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    Q_UNUSED_PAR(me);
    return status_;
}

//${SFs::TstSM5::SM::t1::t2::t3::t4::t5::t6::t7::t8} .........................
//${SFs::TstSM5::SM::t1::t2::t3::t4::t5::t6::t7::t8}
static QState TstSM5_t8_e(TstSM5 * const me) {
    //
    Q_UNUSED_PAR(me);
    return QM_ENTRY(&TstSM5_t8_s);
}
//${SFs::TstSM5::SM::t1::t2::t3::t4::t5::t6::t7::t8}
static QState TstSM5_t8_x(TstSM5 * const me) {
    //
    (void)me; // unused parameter
    return QM_EXIT(&TstSM5_t8_s);
}
//${SFs::TstSM5::SM::t1::t2::t3::t4::t5::t6::t7::t8::initial}
static QState TstSM5_t8_i(TstSM5 * const me) {
    //${SFs::TstSM5::SM::t1::t2::t3::t4::t5::t6::t7::t8::initial}
    static QMTranActTable const tatbl_ = { // tran-action table
        &TstSM5_t9_s, // target state
        {
            Q_ACTION_NULL // zero terminator
        }
    };
    return QM_TRAN_INIT(&tatbl_);
}
//${SFs::TstSM5::SM::t1::t2::t3::t4::t5::t6::t7::t8}
static QState TstSM5_t8(TstSM5 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    Q_UNUSED_PAR(me);
    return status_;
}

//${SFs::TstSM5::SM::t1::t2::t3::t4::t5::t6::t7::t8::t9} .....................
//${SFs::TstSM5::SM::t1::t2::t3::t4::t5::t6::t7::t8::t9}
static QState TstSM5_t9_x(TstSM5 * const me) {
    //
    (void)me; // unused parameter
    return QM_EXIT(&TstSM5_t9_s);
}
//${SFs::TstSM5::SM::t1::t2::t3::t4::t5::t6::t7::t8::t9}
static QState TstSM5_t9(TstSM5 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    Q_UNUSED_PAR(me);
    return status_;
}
//$enddef${SFs} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
