//$file${.::reminder.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: reminder.qm
// File:  ${.::reminder.c}
//
// This code has been generated by QM 7.0.2 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::reminder.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpc.h"        // QP/C real-time event framework
#include "bsp.h"        // Board Support Package interface
#include "app.h"        // Application

//Q_DEFINE_THIS_FILE

//$declare${AOs::Sensor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Sensor} .............................................................
typedef struct Sensor {
// protected:
    QActive super;

// public:
    QTimeEvt timeEvt;
    uint16_t pollCtr;
    uint16_t procCtr;
} Sensor;

extern Sensor Sensor_inst;

// protected:
static QState Sensor_initial(Sensor * const me, void const * const par);
static QState Sensor_final(Sensor * const me, QEvt const * const e);
static QState Sensor_polling(Sensor * const me, QEvt const * const e);
static QState Sensor_processing(Sensor * const me, QEvt const * const e);
static QState Sensor_idle(Sensor * const me, QEvt const * const e);
static QState Sensor_busy(Sensor * const me, QEvt const * const e);
//$enddecl${AOs::Sensor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${App} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${App::Sensor_ctor} ........................................................
void Sensor_ctor(void) {
    Sensor * const me = &Sensor_inst;
    QActive_ctor(&me->super, Q_STATE_CAST(&Sensor_initial));
    QTimeEvt_ctorX(&me->timeEvt, (QActive *)me, TIMEOUT_SIG, 0U);
}

//${App::AO_Sensor} ..........................................................
QActive * const AO_Sensor = (QActive *)&Sensor_inst;
//$enddef${App} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::Sensor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Sensor} .............................................................
Sensor Sensor_inst;

//${AOs::Sensor::SM} .........................................................
static QState Sensor_initial(Sensor * const me, void const * const par) {
    //${AOs::Sensor::SM::initial}
    Q_UNUSED_PAR(par);

    me->pollCtr = 0U;
    me->procCtr = 0U;
    return Q_TRAN(&Sensor_polling);
}

//${AOs::Sensor::SM::final} ..................................................
static QState Sensor_final(Sensor * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Sensor::SM::final}
        case Q_ENTRY_SIG: {
            QF_stop(); // terminate the application
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${AOs::Sensor::SM::polling} ................................................
static QState Sensor_polling(Sensor * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Sensor::SM::polling}
        case Q_ENTRY_SIG: {
            // periodic timeout in 1/2 second and every 1/2 second
            QTimeEvt_armX(&me->timeEvt,
                BSP_TICKS_PER_SEC/2, BSP_TICKS_PER_SEC/2);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Sensor::SM::polling}
        case Q_EXIT_SIG: {
            QTimeEvt_disarm(&me->timeEvt);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Sensor::SM::polling::initial}
        case Q_INIT_SIG: {
            status_ = Q_TRAN(&Sensor_processing);
            break;
        }
        //${AOs::Sensor::SM::polling::TIMEOUT}
        case TIMEOUT_SIG: {
            // NOTE: this constant event is statically pre-allocated.
            // It can be posted/published as any other event.
            //
            static const QEvt reminderEvt = QEVT_INITIALIZER(DATA_READY_SIG);

            ++me->pollCtr;
            BSP_showMsg("polling %3d\n", me->pollCtr);
            if ((me->pollCtr & 0x3U) == 0U) {  // modulo 4
                QACTIVE_POST(&me->super, &reminderEvt, me);
            }
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Sensor::SM::polling::TERMINATE}
        case TERMINATE_SIG: {
            status_ = Q_TRAN(&Sensor_final);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${AOs::Sensor::SM::polling::processing} ....................................
static QState Sensor_processing(Sensor * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Sensor::SM::polling::processing::initial}
        case Q_INIT_SIG: {
            status_ = Q_TRAN(&Sensor_idle);
            break;
        }
        default: {
            status_ = Q_SUPER(&Sensor_polling);
            break;
        }
    }
    return status_;
}

//${AOs::Sensor::SM::polling::processing::idle} ..............................
static QState Sensor_idle(Sensor * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Sensor::SM::polling::processing::idle}
        case Q_ENTRY_SIG: {
            BSP_showMsg("idle-ENTRY;\n", 0U);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Sensor::SM::polling::processing::idle::DATA_READY}
        case DATA_READY_SIG: {
            status_ = Q_TRAN(&Sensor_busy);
            break;
        }
        default: {
            status_ = Q_SUPER(&Sensor_processing);
            break;
        }
    }
    return status_;
}

//${AOs::Sensor::SM::polling::processing::busy} ..............................
static QState Sensor_busy(Sensor * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Sensor::SM::polling::processing::busy}
        case Q_ENTRY_SIG: {
            BSP_showMsg("busy-ENTRY;\n", 0);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Sensor::SM::polling::processing::busy::TIMEOUT}
        case TIMEOUT_SIG: {
            ++me->procCtr;
            BSP_showMsg("processing %3d\n", me->procCtr);
            //${AOs::Sensor::SM::polling::processing::busy::TIMEOUT::[(me->procCtr&0x1U)==0U]}
            if ((me->procCtr & 0x1U) == 0U) {
                status_ = Q_TRAN(&Sensor_idle);
            }
            //${AOs::Sensor::SM::polling::processing::busy::TIMEOUT::[else]}
            else {
                status_ = Q_HANDLED();
            }
            break;
        }
        default: {
            status_ = Q_SUPER(&Sensor_processing);
            break;
        }
    }
    return status_;
}
//$enddef${AOs::Sensor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
