/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.40.0.0
 *
 * Project: 'project'
 * Target:  'rel'
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File:
 */
#define CMSIS_device_header "stm32c0xx.h"

/* QuantumLeaps::RTEF&qpc:Event Processor&qep@8.0.0 */
#define RTE_RTEF_QPC_QEP        /* QP/C QEP */
/* QuantumLeaps::RTEF&qpc:Framework&qf@8.0.0 */
#define RTE_RTEF_QPC_QF         /* QP/C QF */
/* QuantumLeaps::RTEF&qpc:Real-Time Kernel&qk@8.0.0 */
#define RTE_RTEF_QPC_QK         /* QP/C QK kernel */


#endif /* RTE_COMPONENTS_H */
