//$file${src::gizmo.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: gizmo.qm
// File:  ${src::gizmo.c}
//
// This code has been generated by QM 7.0.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${src::gizmo.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpc.h"
#include "bsp.h"
#include "gizmo.h"

//Q_DEFINE_THIS_MODULE("gizmo")

//$declare${AOs::Gizmo} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Gizmo} ..............................................................
typedef struct Gizmo {
// protected:
    QActive super;

// public:
} Gizmo;
extern Gizmo Gizmo_inst;

// protected:
static QState Gizmo_initial(Gizmo * const me, void const * const par);
static QState Gizmo_initialize(Gizmo * const me, QEvt const * const e);
static QState Gizmo_on_battery(Gizmo * const me, QEvt const * const e);
static QState Gizmo_on_mains(Gizmo * const me, QEvt const * const e);
//$enddecl${AOs::Gizmo} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::AO_Gizmo} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::AO_Gizmo} ...........................................................
QActive * const AO_Gizmo = &Gizmo_inst.super;
//$enddef${AOs::AO_Gizmo} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::Gizmo_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Gizmo_ctor} .........................................................
void Gizmo_ctor(void) {
    Gizmo *me = &Gizmo_inst;
    QActive_ctor(&me->super, Q_STATE_CAST(&Gizmo_initial));
}
//$enddef${AOs::Gizmo_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::Gizmo} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Gizmo} ..............................................................
Gizmo Gizmo_inst;

//${AOs::Gizmo::SM} ..........................................................
static QState Gizmo_initial(Gizmo * const me, void const * const par) {
    //${AOs::Gizmo::SM::initial}
    Q_UNUSED_PAR(par);

    QS_FUN_DICTIONARY(&Gizmo_initialize);
    QS_FUN_DICTIONARY(&Gizmo_on_battery);
    QS_FUN_DICTIONARY(&Gizmo_on_mains);

    return Q_TRAN(&Gizmo_initialize);
}

//${AOs::Gizmo::SM::initialize} ..............................................
static QState Gizmo_initialize(Gizmo * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Gizmo::SM::initialize}
        case Q_ENTRY_SIG: {
            static QEvt const startEvt = QEVT_INITIALIZER(START_SIG);
            QACTIVE_POST(&me->super, &startEvt, me); // self-post
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Gizmo::SM::initialize::START}
        case START_SIG: {
            QS_BEGIN_ID(QS_USER1, me->super.prio)
               QS_STR("START");
            QS_END()
            //${AOs::Gizmo::SM::initialize::START::[BSP_getStatus()]}
            if (BSP_getStatus()) {
                status_ = Q_TRAN(&Gizmo_on_mains);
            }
            //${AOs::Gizmo::SM::initialize::START::[else]}
            else {
                status_ = Q_TRAN(&Gizmo_on_battery);
            }
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${AOs::Gizmo::SM::on_battery} ..............................................
static QState Gizmo_on_battery(Gizmo * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${AOs::Gizmo::SM::on_mains} ................................................
static QState Gizmo_on_mains(Gizmo * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
//$enddef${AOs::Gizmo} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
