//$file${.::blinky0.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: low-power.qm
// File:  ${.::blinky0.c}
//
// This code has been generated by QM 7.0.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::blinky0.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpc.h"
#include "low_power.h"
#include "bsp.h"

//Q_DEFINE_THIS_FILE

//$declare${AOs::Blinky0} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Blinky0} ............................................................
typedef struct Blinky0 {
// protected:
    QActive super;

// private:
    QTimeEvt timeEvt0;

// public:

// private:
    uint8_t count;
} Blinky0;
extern Blinky0 Blinky0_instance;

// protected:
static QState Blinky0_initial(Blinky0 * const me, void const * const par);
static QState Blinky0_active(Blinky0 * const me, QEvt const * const e);
static QState Blinky0_on(Blinky0 * const me, QEvt const * const e);
static QState Blinky0_off(Blinky0 * const me, QEvt const * const e);
static QState Blinky0_inactive(Blinky0 * const me, QEvt const * const e);
//$enddecl${AOs::Blinky0} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::AO_Blinky0} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::AO_Blinky0} .........................................................
QActive * const AO_Blinky0 = &Blinky0_instance.super;
//$enddef${AOs::AO_Blinky0} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$define${AOs::Blinky0} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Blinky0} ............................................................
Blinky0 Blinky0_instance;

//${AOs::Blinky0::SM} ........................................................
static QState Blinky0_initial(Blinky0 * const me, void const * const par) {
    //${AOs::Blinky0::SM::initial}
    (void)par; // unused parameter
    QActive_subscribe(&me->super, BTN_PRESSED_SIG);

    QS_FUN_DICTIONARY(&Blinky0_active);
    QS_FUN_DICTIONARY(&Blinky0_on);
    QS_FUN_DICTIONARY(&Blinky0_off);
    QS_FUN_DICTIONARY(&Blinky0_inactive);

    return Q_TRAN(&Blinky0_active);
}

//${AOs::Blinky0::SM::active} ................................................
static QState Blinky0_active(Blinky0 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Blinky0::SM::active}
        case Q_ENTRY_SIG: {
            BSP_tickRate0_on();
            me->count = 4U;
            QTimeEvt_armX(&me->timeEvt0, 2U, 2U);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Blinky0::SM::active}
        case Q_EXIT_SIG: {
            QTimeEvt_disarm(&me->timeEvt0);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Blinky0::SM::active::initial}
        case Q_INIT_SIG: {
            status_ = Q_TRAN(&Blinky0_on);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${AOs::Blinky0::SM::active::on} ............................................
static QState Blinky0_on(Blinky0 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Blinky0::SM::active::on}
        case Q_ENTRY_SIG: {
            BSP_led0_on();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Blinky0::SM::active::on}
        case Q_EXIT_SIG: {
            BSP_led0_off();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Blinky0::SM::active::on::TIMEOUT0}
        case TIMEOUT0_SIG: {
            --me->count;
            //${AOs::Blinky0::SM::active::on::TIMEOUT0::[me->count>0]}
            if (me->count > 0) {
                status_ = Q_TRAN(&Blinky0_off);
            }
            //${AOs::Blinky0::SM::active::on::TIMEOUT0::[else]}
            else {
                status_ = Q_TRAN(&Blinky0_inactive);
            }
            break;
        }
        default: {
            status_ = Q_SUPER(&Blinky0_active);
            break;
        }
    }
    return status_;
}

//${AOs::Blinky0::SM::active::off} ...........................................
static QState Blinky0_off(Blinky0 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Blinky0::SM::active::off::TIMEOUT0}
        case TIMEOUT0_SIG: {
            status_ = Q_TRAN(&Blinky0_on);
            break;
        }
        default: {
            status_ = Q_SUPER(&Blinky0_active);
            break;
        }
    }
    return status_;
}

//${AOs::Blinky0::SM::inactive} ..............................................
static QState Blinky0_inactive(Blinky0 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Blinky0::SM::inactive::BTN_PRESSED}
        case BTN_PRESSED_SIG: {
            status_ = Q_TRAN(&Blinky0_active);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
//$enddef${AOs::Blinky0} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$define${AOs::Blinky0_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Blinky0_ctor} .......................................................
void Blinky0_ctor(void) {
    Blinky0 *me = &Blinky0_instance;
    QActive_ctor(&me->super, Q_STATE_CAST(&Blinky0_initial));
    QTimeEvt_ctorX(&me->timeEvt0, &me->super, TIMEOUT0_SIG, 0U);
}
//$enddef${AOs::Blinky0_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

