//$file${.::bsp.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: low-power.qm
// File:  ${.::bsp.h}
//
// This code has been generated by QM 7.0.2 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::bsp.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef BSP_H_
#define BSP_H_

// The following ticks-per-second constants determine the speed of the app.
// The default (#if 1) is the SLOW speed for humans to see the blinking.
// Change the #if 1 into #if 0 for FAST speed appropriate for logic analyzers.
//
#if 1
    #define BSP_TICKS0_PER_SEC   2U
    #define BSP_TICKS1_PER_SEC   20U
#else
    #define BSP_TICKS0_PER_SEC   200U
    #define BSP_TICKS1_PER_SEC   2000U
#endif

#if QF_MAX_TICK_RATE < 2
    #error this application requires 2 clock tick rates
#endif

void BSP_init(void const * const arg);

void BSP_led0_on(void);
void BSP_led0_off(void);

void BSP_led1_on(void);
void BSP_led1_off(void);

void BSP_tickRate0_on(void);
void BSP_tickRate1_on(void);

#endif // BSP_H_
