//$file${.::table.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: dpp_console.qm
// File:  ${.::table.c}
//
// This code has been generated by QM 7.0.2 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::table.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpc.h"      // QP/C real-time event framework
#include "bsp.h"      // Board Support Package
#include "app.h"      // Application interface

Q_DEFINE_THIS_FILE

//----------------------------------------------------------------------------
// helper function to provide the RIGHT neighbor of a Philo[n]
static inline uint8_t right(uint8_t const n) {
    return (uint8_t)((n + (N_PHILO - 1U)) % N_PHILO);
}

// helper function to provide the LEFT neighbor of a Philo[n]
static inline uint8_t left(uint8_t const n) {
    return (uint8_t)((n + 1U) % N_PHILO);
}

#define FREE ((uint8_t)0U)
#define USED ((uint8_t)1U)

#define THINKING "thinking"
#define HUNGRY   "hungry  "
#define EATING   "eating  "

//----------------------------------------------------------------------------
//$declare${AOs::Table} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Table} ..............................................................
typedef struct Table {
// protected:
    QMActive super;

// private:
    uint8_t fork[N_PHILO];
    bool isHungry[N_PHILO];

// public:
} Table;

extern Table Table_inst;

// protected:
static QState Table_initial(Table * const me, void const * const par);
static QState Table_active  (Table * const me, QEvt const * const e);
static QMState const Table_active_s = {
    QM_STATE_NULL, // superstate (top)
    Q_STATE_CAST(&Table_active),
    Q_ACTION_NULL, // no entry action
    Q_ACTION_NULL, // no exit action
    Q_ACTION_NULL  // no initial tran.
};
static QState Table_serving  (Table * const me, QEvt const * const e);
static QState Table_serving_e(Table * const me);
static QMState const Table_serving_s = {
    &Table_active_s, // superstate
    Q_STATE_CAST(&Table_serving),
    Q_ACTION_CAST(&Table_serving_e),
    Q_ACTION_NULL, // no exit action
    Q_ACTION_NULL  // no initial tran.
};
static QState Table_paused  (Table * const me, QEvt const * const e);
static QState Table_paused_e(Table * const me);
static QState Table_paused_x(Table * const me);
static QMState const Table_paused_s = {
    &Table_active_s, // superstate
    Q_STATE_CAST(&Table_paused),
    Q_ACTION_CAST(&Table_paused_e),
    Q_ACTION_CAST(&Table_paused_x),
    Q_ACTION_NULL  // no initial tran.
};
//$enddecl${AOs::Table} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${App::Table_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${App::Table_ctor} .........................................................
void Table_ctor(void) {
    Table * const me = &Table_inst;
    QMActive_ctor(&me->super, Q_STATE_CAST(&Table_initial));
    for (uint8_t n = 0U; n < N_PHILO; ++n) {
        me->fork[n] = FREE;
        me->isHungry[n] = false;
    }
}
//$enddef${App::Table_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${App::AO_Table} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${App::AO_Table} ...........................................................
QActive * const AO_Table = Q_ACTIVE_UPCAST(&Table_inst);
//$enddef${App::AO_Table} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::Table} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Table} ..............................................................
Table Table_inst;

//${AOs::Table::SM} ..........................................................
static QState Table_initial(Table * const me, void const * const par) {
    //${AOs::Table::SM::initial}
    Q_UNUSED_PAR(par);

    QS_OBJ_DICTIONARY(&Table_inst);

    QActive_subscribe(Q_ACTIVE_UPCAST(me), DONE_SIG);
    QActive_subscribe(Q_ACTIVE_UPCAST(me), PAUSE_SIG);
    QActive_subscribe(Q_ACTIVE_UPCAST(me), SERVE_SIG);
    QActive_subscribe(Q_ACTIVE_UPCAST(me), TEST_SIG);

    for (uint8_t n = 0U; n < N_PHILO; ++n) {
        me->fork[n] = FREE;
        me->isHungry[n] = false;
        BSP_displayPhilStat(n, THINKING);
    }

    QS_FUN_DICTIONARY(&Table_active);
    QS_FUN_DICTIONARY(&Table_serving);
    QS_FUN_DICTIONARY(&Table_paused);

    static struct {
        QMState const *target;
        QActionHandler act[2];
    } const tatbl_ = { // tran-action table
        &Table_serving_s, // target state
        {
            Q_ACTION_CAST(&Table_serving_e), // entry
            Q_ACTION_NULL // zero terminator
        }
    };
    return QM_TRAN_INIT(&tatbl_);
}

//${AOs::Table::SM::active} ..................................................
//${AOs::Table::SM::active}
static QState Table_active(Table * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Table::SM::active::TEST}
        case TEST_SIG: {
            status_ = QM_HANDLED();
            break;
        }
        //${AOs::Table::SM::active::EAT}
        case EAT_SIG: {
            Q_ERROR();
            status_ = QM_HANDLED();
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    Q_UNUSED_PAR(me);
    return status_;
}

//${AOs::Table::SM::active::serving} .........................................
//${AOs::Table::SM::active::serving}
static QState Table_serving_e(Table * const me) {
    // give permissions to eat...
    for (uint8_t n = 0U; n < N_PHILO; ++n) {
        if (me->isHungry[n]
            && (me->fork[left(n)] == FREE)
            && (me->fork[n] == FREE))
        {
            me->fork[left(n)] = USED;
            me->fork[n] = USED;
    #ifdef QEVT_PAR_INIT
            TableEvt const *pe = Q_NEW(TableEvt, EAT_SIG, n);
    #else
            TableEvt *pe = Q_NEW(TableEvt, EAT_SIG);
            pe->philoId = n;
    #endif
            QACTIVE_PUBLISH(&pe->super, Q_ACTIVE_UPCAST(me));
            me->isHungry[n] = false;
            BSP_displayPhilStat(n, EATING);
        }
    }
    return QM_ENTRY(&Table_serving_s);
}
//${AOs::Table::SM::active::serving}
static QState Table_serving(Table * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Table::SM::active::serving::HUNGRY}
        case HUNGRY_SIG: {
            uint8_t n = Q_EVT_CAST(TableEvt)->philoId;

            // phil ID must be in range and he must be not hungry
            Q_ASSERT((n < N_PHILO) && (!me->isHungry[n]));

            BSP_displayPhilStat(n, HUNGRY);
            uint8_t m = left(n);
            //${AOs::Table::SM::active::serving::HUNGRY::[bothfree]}
            if ((me->fork[m] == FREE) && (me->fork[n] == FREE)) {
                me->fork[m] = USED;
                me->fork[n] = USED;
                #ifdef QEVT_PAR_INIT
                TableEvt const *pe = Q_NEW(TableEvt, EAT_SIG, n);
                #else
                TableEvt *pe = Q_NEW(TableEvt, EAT_SIG);
                pe->philoId = n;
                #endif
                QACTIVE_PUBLISH(&pe->super, Q_ACTIVE_UPCAST(me));
                BSP_displayPhilStat(n, EATING);
                status_ = QM_HANDLED();
            }
            //${AOs::Table::SM::active::serving::HUNGRY::[else]}
            else {
                me->isHungry[n] = true;
                status_ = QM_HANDLED();
            }
            break;
        }
        //${AOs::Table::SM::active::serving::DONE}
        case DONE_SIG: {
            uint8_t n = Q_EVT_CAST(TableEvt)->philoId;

            // phil ID must be in range and he must be not hungry
            Q_ASSERT((n < N_PHILO) && (!me->isHungry[n]));

            BSP_displayPhilStat(n, THINKING);
            uint8_t m = left(n);

            // both forks of Phil[n] must be used
            Q_ASSERT((me->fork[n] == USED) && (me->fork[m] == USED));

            me->fork[m] = FREE;
            me->fork[n] = FREE;
            m = right(n); // check the right neighbor

            if (me->isHungry[m] && (me->fork[m] == FREE)) {
                me->fork[n] = USED;
                me->fork[m] = USED;
                me->isHungry[m] = false;
            #ifdef QEVT_PAR_INIT
                TableEvt const *pe = Q_NEW(TableEvt, EAT_SIG, m);
            #else
                TableEvt *pe = Q_NEW(TableEvt, EAT_SIG);
                pe->philoId = m;
            #endif
                QACTIVE_PUBLISH(&pe->super, Q_ACTIVE_UPCAST(me));
                BSP_displayPhilStat(m, EATING);
            }
            m = left(n); // check the left neighbor
            n = left(m); // left fork of the left neighbor
            if (me->isHungry[m] && (me->fork[n] == FREE)) {
                me->fork[m] = USED;
                me->fork[n] = USED;
                me->isHungry[m] = false;
            #ifdef QEVT_PAR_INIT
                TableEvt const *pe = Q_NEW(TableEvt, EAT_SIG, m);
            #else
                TableEvt *pe = Q_NEW(TableEvt, EAT_SIG);
                pe->philoId = m;
            #endif
                QACTIVE_PUBLISH(&pe->super, Q_ACTIVE_UPCAST(me));
                BSP_displayPhilStat(m, EATING);
            }
            status_ = QM_HANDLED();
            break;
        }
        //${AOs::Table::SM::active::serving::PAUSE}
        case PAUSE_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[2];
            } const tatbl_ = { // tran-action table
                &Table_paused_s, // target state
                {
                    Q_ACTION_CAST(&Table_paused_e), // entry
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

//${AOs::Table::SM::active::paused} ..........................................
//${AOs::Table::SM::active::paused}
static QState Table_paused_e(Table * const me) {
    BSP_displayPaused(1U);
    Q_UNUSED_PAR(me);
    return QM_ENTRY(&Table_paused_s);
}
//${AOs::Table::SM::active::paused}
static QState Table_paused_x(Table * const me) {
    BSP_displayPaused(0U);
    (void)me; // unused parameter
    return QM_EXIT(&Table_paused_s);
}
//${AOs::Table::SM::active::paused}
static QState Table_paused(Table * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Table::SM::active::paused::SERVE}
        case SERVE_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[3];
            } const tatbl_ = { // tran-action table
                &Table_serving_s, // target state
                {
                    Q_ACTION_CAST(&Table_paused_x), // exit
                    Q_ACTION_CAST(&Table_serving_e), // entry
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        //${AOs::Table::SM::active::paused::HUNGRY}
        case HUNGRY_SIG: {
            uint8_t n = Q_EVT_CAST(TableEvt)->philoId;

            // philo ID must be in range and he must be not hungry
            Q_ASSERT((n < N_PHILO) && (!me->isHungry[n]));

            me->isHungry[n] = true;
            BSP_displayPhilStat(n, HUNGRY);
            status_ = QM_HANDLED();
            break;
        }
        //${AOs::Table::SM::active::paused::DONE}
        case DONE_SIG: {
            uint8_t n = Q_EVT_CAST(TableEvt)->philoId;

            // phil ID must be in range and he must be not hungry
            Q_ASSERT((n < N_PHILO) && (!me->isHungry[n]));

            BSP_displayPhilStat(n, THINKING);
            uint8_t m = left(n);

            // both forks of Phil[n] must be used
            Q_ASSERT((me->fork[n] == USED) && (me->fork[m] == USED));

            me->fork[m] = FREE;
            me->fork[n] = FREE;
            status_ = QM_HANDLED();
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}
//$enddef${AOs::Table} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
